#!/usr/bin/env python3
"""Generate calibNtcCount[101] for App/Src/bms_calib.c.

The divider is ratiometric - VDDA cancels - so a count depends only on the
fixed resistor and the NTC's resistance:

    count(T) = 4095 * Rfixed / (Rfixed + Rt(T))

Two ways to describe the NTC:

  --beta      one B value and R25, from the part's datasheet. Simple, but a
              single B drifts a degree or two at the ends of 0..100 degC.
  --point     three measured (degC, ohm) pairs, fitted with Steinhart-Hart.
              Needs no part number and is accurate across the whole span.

  gen_ntc_table.py --rfixed 10000 --beta 3435 --r25 10000
  gen_ntc_table.py --rfixed 9960 --point 0:27515 --point 25:10000 --point 100:983
"""

import argparse
import math
import sys

K = 273.15
ADC_FULL = 4095


def rt_from_beta(beta: float, r25: float):
    return lambda t: r25 * math.exp(beta * (1.0 / (t + K) - 1.0 / (25.0 + K)))


def rt_from_points(points):
    """Steinhart-Hart through exactly three (degC, ohm) pairs: 1/T = a + b*lnR + c*lnR^3."""
    (t1, r1), (t2, r2), (t3, r3) = points
    l1, l2, l3 = math.log(r1), math.log(r2), math.log(r3)
    y1, y2, y3 = 1.0 / (t1 + K), 1.0 / (t2 + K), 1.0 / (t3 + K)
    g2 = (y2 - y1) / (l2 - l1)
    g3 = (y3 - y1) / (l3 - l1)
    c = ((g3 - g2) / (l3 - l2)) / (l1 + l2 + l3)
    b = g2 - c * (l1 * l1 + l1 * l2 + l2 * l2)
    a = y1 - (b + l1 * l1 * c) * l1

    def rt(t):
        # invert Steinhart-Hart for R at temperature t (Cardano)
        y = (a - 1.0 / (t + K)) / c
        x = math.sqrt((b / (3.0 * c)) ** 3 + (y * y) / 4.0)
        return math.exp((x - y / 2.0) ** (1.0 / 3.0) - (x + y / 2.0) ** (1.0 / 3.0))

    return rt


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--rfixed", type=float, required=True,
                   help="measured fixed resistor, ohm (PC0 to GND, probe unplugged)")
    p.add_argument("--beta", type=float, help="NTC B value, K")
    p.add_argument("--r25", type=float, default=10000.0, help="NTC resistance at 25 degC (default 10000)")
    p.add_argument("--point", action="append", metavar="DEGC:OHM",
                   help="measured pair; give exactly three for a Steinhart-Hart fit")
    args = p.parse_args()

    if args.point:
        if len(args.point) != 3:
            p.error("--point takes exactly three pairs")
        pts = []
        for s in args.point:
            t, r = s.split(":")
            pts.append((float(t), float(r)))
        rt = rt_from_points(pts)
        how = "Steinhart-Hart through " + ", ".join(f"{t:g}degC/{r:g}ohm" for t, r in pts)
    elif args.beta:
        rt = rt_from_beta(args.beta, args.r25)
        how = f"B={args.beta:g} K, R25={args.r25:g} ohm"
    else:
        p.error("give --beta or three --point pairs")

    counts = [round(ADC_FULL * args.rfixed / (args.rfixed + rt(i))) for i in range(101)]

    bad = [i for i in range(100) if counts[i + 1] <= counts[i]]
    if bad:
        print(f"ERROR: not strictly increasing at index {bad[0]} - "
              "CALIB_NtcCountIsMonotonic would halt at init", file=sys.stderr)
        return 1

    print(f"/* {how}, Rfixed={args.rfixed:g} ohm. Generated by "
          "tests/oracle/gen_ntc_table.py */")
    print("const uint16_t calibNtcCount[101] = {")
    for row in range(0, 101, 10):
        chunk = counts[row:row + 10]
        print("    " + ", ".join(f"{c}" for c in chunk) + ("," if row + 10 < 101 else ""))
    print("};")

    print(f"\n/* span {counts[0]}..{counts[100]} counts;"
          f" check NTC_OPEN_BELOW / NTC_SHORT_ABOVE in app_adc.c */", file=sys.stderr)
    print("/* spot values:", file=sys.stderr)
    for t in (0, 25, 40, 60, 80, 100):
        print(f"     {t:3d} degC -> Rt {rt(t):8.0f} ohm -> count {counts[t]:4d}", file=sys.stderr)
    print("*/", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
