/**
 * @file CAN_DB.h
 *
 * @brief This header file was generated by cantools version 0.1.dev1949+g29b75602e.d20260911 Fri Sep 11 16:58:15 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef CAN_DB_H
#define CAN_DB_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define BMSMASTER_NODE_FRAME_ID (0x80u)
#define BMSMASTER_END_FRAME_ID (0x9fu)
#define BMSMASTER_MASTERVOLTCURRTEMP_FRAME_ID (0x82u)
#define BMSMASTER_PCBSTHERM1TEMP_FRAME_ID (0x83u)
#define BMSMASTER_PCBSTHERM2TEMP_FRAME_ID (0x84u)
#define BMSMASTER_PCBSTHERM3TEMP_FRAME_ID (0x85u)
#define BMSMASTER_PCBSTHERM4TEMP_FRAME_ID (0x86u)
#define BMSMASTER_PCBSTHERM5TEMP_FRAME_ID (0x87u)
#define BMSMASTER_PCBSTHERM6TEMP_FRAME_ID (0x88u)
#define BMSMASTER_PCBSTHERM7TEMP_FRAME_ID (0x89u)
#define BMSMASTER_PCBSTHERM8TEMP_FRAME_ID (0x8au)
#define BMSMASTER_PCBSTHERM9TEMP_FRAME_ID (0x8bu)
#define COOLINGBACK_FAN_FRAME_ID (0x4e1u)
#define BMSMASTER_JK_PACK_FRAME_ID (0x8cu)
#define BMSMASTER_JK_CELLS_1_4_FRAME_ID (0x8du)
#define BMSMASTER_JK_CELLS_5_8_FRAME_ID (0x8eu)
#define BMSMASTER_JK_CELLS_9_12_FRAME_ID (0x8fu)
#define BMSMASTER_JK_CELLS_13_16_FRAME_ID (0x90u)
#define BMSMASTER_JK_CELLS_17_20_FRAME_ID (0x91u)
#define BMSMASTER_JK_CELLS_21_FRAME_ID (0x92u)
#define BMSMASTER_JK_TEMP_FRAME_ID (0x93u)
#define BMSMASTER_JK_CYCLESTATS_FRAME_ID (0x94u)

/* Frame lengths in bytes. */
#define BMSMASTER_NODE_LENGTH (8u)
#define BMSMASTER_END_LENGTH (8u)
#define BMSMASTER_MASTERVOLTCURRTEMP_LENGTH (6u)
#define BMSMASTER_PCBSTHERM1TEMP_LENGTH (7u)
#define BMSMASTER_PCBSTHERM2TEMP_LENGTH (7u)
#define BMSMASTER_PCBSTHERM3TEMP_LENGTH (7u)
#define BMSMASTER_PCBSTHERM4TEMP_LENGTH (7u)
#define BMSMASTER_PCBSTHERM5TEMP_LENGTH (7u)
#define BMSMASTER_PCBSTHERM6TEMP_LENGTH (7u)
#define BMSMASTER_PCBSTHERM7TEMP_LENGTH (7u)
#define BMSMASTER_PCBSTHERM8TEMP_LENGTH (7u)
#define BMSMASTER_PCBSTHERM9TEMP_LENGTH (7u)
#define COOLINGBACK_FAN_LENGTH (2u)
#define BMSMASTER_JK_PACK_LENGTH (8u)
#define BMSMASTER_JK_CELLS_1_4_LENGTH (8u)
#define BMSMASTER_JK_CELLS_5_8_LENGTH (8u)
#define BMSMASTER_JK_CELLS_9_12_LENGTH (8u)
#define BMSMASTER_JK_CELLS_13_16_LENGTH (8u)
#define BMSMASTER_JK_CELLS_17_20_LENGTH (8u)
#define BMSMASTER_JK_CELLS_21_LENGTH (2u)
#define BMSMASTER_JK_TEMP_LENGTH (8u)
#define BMSMASTER_JK_CYCLESTATS_LENGTH (8u)

/* Extended or standard frame types. */
#define BMSMASTER_NODE_IS_EXTENDED (0)
#define BMSMASTER_END_IS_EXTENDED (0)
#define BMSMASTER_MASTERVOLTCURRTEMP_IS_EXTENDED (0)
#define BMSMASTER_PCBSTHERM1TEMP_IS_EXTENDED (0)
#define BMSMASTER_PCBSTHERM2TEMP_IS_EXTENDED (0)
#define BMSMASTER_PCBSTHERM3TEMP_IS_EXTENDED (0)
#define BMSMASTER_PCBSTHERM4TEMP_IS_EXTENDED (0)
#define BMSMASTER_PCBSTHERM5TEMP_IS_EXTENDED (0)
#define BMSMASTER_PCBSTHERM6TEMP_IS_EXTENDED (0)
#define BMSMASTER_PCBSTHERM7TEMP_IS_EXTENDED (0)
#define BMSMASTER_PCBSTHERM8TEMP_IS_EXTENDED (0)
#define BMSMASTER_PCBSTHERM9TEMP_IS_EXTENDED (0)
#define COOLINGBACK_FAN_IS_EXTENDED (0)
#define BMSMASTER_JK_PACK_IS_EXTENDED (0)
#define BMSMASTER_JK_CELLS_1_4_IS_EXTENDED (0)
#define BMSMASTER_JK_CELLS_5_8_IS_EXTENDED (0)
#define BMSMASTER_JK_CELLS_9_12_IS_EXTENDED (0)
#define BMSMASTER_JK_CELLS_13_16_IS_EXTENDED (0)
#define BMSMASTER_JK_CELLS_17_20_IS_EXTENDED (0)
#define BMSMASTER_JK_CELLS_21_IS_EXTENDED (0)
#define BMSMASTER_JK_TEMP_IS_EXTENDED (0)
#define BMSMASTER_JK_CYCLESTATS_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define BMSMASTER_NODE_CYCLE_TIME_MS (5000u)
#define BMSMASTER_END_CYCLE_TIME_MS (1000u)
#define BMSMASTER_MASTERVOLTCURRTEMP_CYCLE_TIME_MS (500u)
#define BMSMASTER_PCBSTHERM1TEMP_CYCLE_TIME_MS (1000u)
#define BMSMASTER_PCBSTHERM2TEMP_CYCLE_TIME_MS (1000u)
#define BMSMASTER_PCBSTHERM3TEMP_CYCLE_TIME_MS (1000u)
#define BMSMASTER_PCBSTHERM4TEMP_CYCLE_TIME_MS (1000u)
#define BMSMASTER_PCBSTHERM5TEMP_CYCLE_TIME_MS (1000u)
#define BMSMASTER_PCBSTHERM6TEMP_CYCLE_TIME_MS (1000u)
#define BMSMASTER_PCBSTHERM7TEMP_CYCLE_TIME_MS (1000u)
#define BMSMASTER_PCBSTHERM8TEMP_CYCLE_TIME_MS (1000u)
#define BMSMASTER_PCBSTHERM9TEMP_CYCLE_TIME_MS (1000u)
#define COOLINGBACK_FAN_CYCLE_TIME_MS (100u)
#define BMSMASTER_JK_PACK_CYCLE_TIME_MS (1000u)
#define BMSMASTER_JK_CELLS_1_4_CYCLE_TIME_MS (1000u)
#define BMSMASTER_JK_CELLS_5_8_CYCLE_TIME_MS (1000u)
#define BMSMASTER_JK_CELLS_9_12_CYCLE_TIME_MS (1000u)
#define BMSMASTER_JK_CELLS_13_16_CYCLE_TIME_MS (1000u)
#define BMSMASTER_JK_CELLS_17_20_CYCLE_TIME_MS (1000u)
#define BMSMASTER_JK_CELLS_21_CYCLE_TIME_MS (1000u)
#define BMSMASTER_JK_TEMP_CYCLE_TIME_MS (1000u)
#define BMSMASTER_JK_CYCLESTATS_CYCLE_TIME_MS (1000u)

/* Signal choices. */


/* Frame Names. */
#define BMSMASTER_NODE_NAME "BMSMaster_NODE"
#define BMSMASTER_END_NAME "BMSMaster_END"
#define BMSMASTER_MASTERVOLTCURRTEMP_NAME "BMSMaster_MasterVoltCurrTemp"
#define BMSMASTER_PCBSTHERM1TEMP_NAME "BMSMaster_PCBsTherm1Temp"
#define BMSMASTER_PCBSTHERM2TEMP_NAME "BMSMaster_PCBsTherm2Temp"
#define BMSMASTER_PCBSTHERM3TEMP_NAME "BMSMaster_PCBsTherm3Temp"
#define BMSMASTER_PCBSTHERM4TEMP_NAME "BMSMaster_PCBsTherm4Temp"
#define BMSMASTER_PCBSTHERM5TEMP_NAME "BMSMaster_PCBsTherm5Temp"
#define BMSMASTER_PCBSTHERM6TEMP_NAME "BMSMaster_PCBsTherm6Temp"
#define BMSMASTER_PCBSTHERM7TEMP_NAME "BMSMaster_PCBsTherm7Temp"
#define BMSMASTER_PCBSTHERM8TEMP_NAME "BMSMaster_PCBsTherm8Temp"
#define BMSMASTER_PCBSTHERM9TEMP_NAME "BMSMaster_PCBsTherm9Temp"
#define COOLINGBACK_FAN_NAME "CoolingBack_Fan"
#define BMSMASTER_JK_PACK_NAME "BMSMaster_JK_Pack"
#define BMSMASTER_JK_CELLS_1_4_NAME "BMSMaster_JK_Cells_1_4"
#define BMSMASTER_JK_CELLS_5_8_NAME "BMSMaster_JK_Cells_5_8"
#define BMSMASTER_JK_CELLS_9_12_NAME "BMSMaster_JK_Cells_9_12"
#define BMSMASTER_JK_CELLS_13_16_NAME "BMSMaster_JK_Cells_13_16"
#define BMSMASTER_JK_CELLS_17_20_NAME "BMSMaster_JK_Cells_17_20"
#define BMSMASTER_JK_CELLS_21_NAME "BMSMaster_JK_Cells_21"
#define BMSMASTER_JK_TEMP_NAME "BMSMaster_JK_Temp"
#define BMSMASTER_JK_CYCLESTATS_NAME "BMSMaster_JK_CycleStats"

/* Signal Names. */
#define BMSMASTER_NODE_ERROR_CODE_NAME "Error_Code"
#define BMSMASTER_NODE_RESERVED_NAME "Reserved"
#define BMSMASTER_NODE_SEVERITY_NAME "Severity"
#define BMSMASTER_NODE_NODE_EXECUTION_HALTED_NAME "Node_Execution_Halted"
#define BMSMASTER_NODE_ERROR_SPECIFIC_DATA_NAME "Error_Specific_Data"
#define BMSMASTER_MASTERVOLTCURRTEMP_BMSMASTER_MASTERBATTERYVOLTAGE_NAME "BMSMaster_MasterBatteryVoltage"
#define BMSMASTER_MASTERVOLTCURRTEMP_BMSMASTER_MASTERBATTERYCURRENT_NAME "BMSMaster_MasterBatteryCurrent"
#define BMSMASTER_MASTERVOLTCURRTEMP_BMSMASTE_MASTERBATTERYTEMPERATUR_NAME "BMSMaste_MasterBatteryTemperatur"
#define BMSMASTER_PCBSTHERM1TEMP_BMSMASTER_PCB1THERM1TEMP_NAME "BMSMaster_PCB1Therm1Temp"
#define BMSMASTER_PCBSTHERM1TEMP_BMSMASTER_PCB2THERM1TEMP_NAME "BMSMaster_PCB2Therm1Temp"
#define BMSMASTER_PCBSTHERM1TEMP_BMSMASTER_PCB3THERM1TEMP_NAME "BMSMaster_PCB3Therm1Temp"
#define BMSMASTER_PCBSTHERM1TEMP_BMSMASTER_PCB4THERM1TEMP_NAME "BMSMaster_PCB4Therm1Temp"
#define BMSMASTER_PCBSTHERM1TEMP_BMSMASTER_PCB5THERM1TEMP_NAME "BMSMaster_PCB5Therm1Temp"
#define BMSMASTER_PCBSTHERM1TEMP_BMSMASTER_PCB6THERM1TEMP_NAME "BMSMaster_PCB6Therm1Temp"
#define BMSMASTER_PCBSTHERM1TEMP_BMSMASTER_PCB7THERM1TEMP_NAME "BMSMaster_PCB7Therm1Temp"
#define BMSMASTER_PCBSTHERM2TEMP_BMSMASTER_PCB1THERM2TEMP_NAME "BMSMaster_PCB1Therm2Temp"
#define BMSMASTER_PCBSTHERM2TEMP_BMSMASTER_PCB2THERM2TEMP_NAME "BMSMaster_PCB2Therm2Temp"
#define BMSMASTER_PCBSTHERM2TEMP_BMSMASTER_PCB3THERM2TEMP_NAME "BMSMaster_PCB3Therm2Temp"
#define BMSMASTER_PCBSTHERM2TEMP_BMSMASTER_PCB4THERM2TEMP_NAME "BMSMaster_PCB4Therm2Temp"
#define BMSMASTER_PCBSTHERM2TEMP_BMSMASTER_PCB5THERM2TEMP_NAME "BMSMaster_PCB5Therm2Temp"
#define BMSMASTER_PCBSTHERM2TEMP_BMSMASTER_PCB6THERM2TEMP_NAME "BMSMaster_PCB6Therm2Temp"
#define BMSMASTER_PCBSTHERM2TEMP_BMSMASTER_PCB7THERM2TEMP_NAME "BMSMaster_PCB7Therm2Temp"
#define BMSMASTER_PCBSTHERM3TEMP_BMSMASTER_PCB1THERM3TEMP_NAME "BMSMaster_PCB1Therm3Temp"
#define BMSMASTER_PCBSTHERM3TEMP_BMSMASTER_PCB2THERM3TEMP_NAME "BMSMaster_PCB2Therm3Temp"
#define BMSMASTER_PCBSTHERM3TEMP_BMSMASTER_PCB3THERM3TEMP_NAME "BMSMaster_PCB3Therm3Temp"
#define BMSMASTER_PCBSTHERM3TEMP_BMSMASTER_PCB4THERM3TEMP_NAME "BMSMaster_PCB4Therm3Temp"
#define BMSMASTER_PCBSTHERM3TEMP_BMSMASTER_PCB5THERM3TEMP_NAME "BMSMaster_PCB5Therm3Temp"
#define BMSMASTER_PCBSTHERM3TEMP_BMSMASTER_PCB6THERM3TEMP_NAME "BMSMaster_PCB6Therm3Temp"
#define BMSMASTER_PCBSTHERM3TEMP_BMSMASTER_PCB7THERM3TEMP_NAME "BMSMaster_PCB7Therm3Temp"
#define BMSMASTER_PCBSTHERM4TEMP_BMSMASTER_PCB1THERM4TEMP_NAME "BMSMaster_PCB1Therm4Temp"
#define BMSMASTER_PCBSTHERM4TEMP_BMSMASTER_PCB2THERM4TEMP_NAME "BMSMaster_PCB2Therm4Temp"
#define BMSMASTER_PCBSTHERM4TEMP_BMSMASTER_PCB3THERM4TEMP_NAME "BMSMaster_PCB3Therm4Temp"
#define BMSMASTER_PCBSTHERM4TEMP_BMSMASTER_PCB4THERM4TEMP_NAME "BMSMaster_PCB4Therm4Temp"
#define BMSMASTER_PCBSTHERM4TEMP_BMSMASTER_PCB5THERM4TEMP_NAME "BMSMaster_PCB5Therm4Temp"
#define BMSMASTER_PCBSTHERM4TEMP_BMSMASTER_PCB6THERM4TEMP_NAME "BMSMaster_PCB6Therm4Temp"
#define BMSMASTER_PCBSTHERM4TEMP_BMSMASTER_PCB7THERM4TEMP_NAME "BMSMaster_PCB7Therm4Temp"
#define BMSMASTER_PCBSTHERM5TEMP_BMSMASTER_PCB1THERM5TEMP_NAME "BMSMaster_PCB1Therm5Temp"
#define BMSMASTER_PCBSTHERM5TEMP_BMSMASTER_PCB2THERM5TEMP_NAME "BMSMaster_PCB2Therm5Temp"
#define BMSMASTER_PCBSTHERM5TEMP_BMSMASTER_PCB3THERM5TEMP_NAME "BMSMaster_PCB3Therm5Temp"
#define BMSMASTER_PCBSTHERM5TEMP_BMSMASTER_PCB4THERM5TEMP_NAME "BMSMaster_PCB4Therm5Temp"
#define BMSMASTER_PCBSTHERM5TEMP_BMSMASTER_PCB5THERM5TEMP_NAME "BMSMaster_PCB5Therm5Temp"
#define BMSMASTER_PCBSTHERM5TEMP_BMSMASTER_PCB6THERM5TEMP_NAME "BMSMaster_PCB6Therm5Temp"
#define BMSMASTER_PCBSTHERM5TEMP_BMSMASTER_PCB7THERM5TEMP_NAME "BMSMaster_PCB7Therm5Temp"
#define BMSMASTER_PCBSTHERM6TEMP_BMSMASTER_PCB1THERM6TEMP_NAME "BMSMaster_PCB1Therm6Temp"
#define BMSMASTER_PCBSTHERM6TEMP_BMSMASTER_PCB2THERM6TEMP_NAME "BMSMaster_PCB2Therm6Temp"
#define BMSMASTER_PCBSTHERM6TEMP_BMSMASTER_PCB3THERM6TEMP_NAME "BMSMaster_PCB3Therm6Temp"
#define BMSMASTER_PCBSTHERM6TEMP_BMSMASTER_PCB4THERM6TEMP_NAME "BMSMaster_PCB4Therm6Temp"
#define BMSMASTER_PCBSTHERM6TEMP_BMSMASTER_PCB5THERM6TEMP_NAME "BMSMaster_PCB5Therm6Temp"
#define BMSMASTER_PCBSTHERM6TEMP_BMSMASTER_PCB6THERM6TEMP_NAME "BMSMaster_PCB6Therm6Temp"
#define BMSMASTER_PCBSTHERM6TEMP_BMSMASTER_PCB7THERM6TEMP_NAME "BMSMaster_PCB7Therm6Temp"
#define BMSMASTER_PCBSTHERM7TEMP_BMSMASTER_PCB1THERM7TEMP_NAME "BMSMaster_PCB1Therm7Temp"
#define BMSMASTER_PCBSTHERM7TEMP_BMSMASTER_PCB2THERM7TEMP_NAME "BMSMaster_PCB2Therm7Temp"
#define BMSMASTER_PCBSTHERM7TEMP_BMSMASTER_PCB3THERM7TEMP_NAME "BMSMaster_PCB3Therm7Temp"
#define BMSMASTER_PCBSTHERM7TEMP_BMSMASTER_PCB4THERM7TEMP_NAME "BMSMaster_PCB4Therm7Temp"
#define BMSMASTER_PCBSTHERM7TEMP_BMSMASTER_PCB5THERM7TEMP_NAME "BMSMaster_PCB5Therm7Temp"
#define BMSMASTER_PCBSTHERM7TEMP_BMSMASTER_PCB6THERM7TEMP_NAME "BMSMaster_PCB6Therm7Temp"
#define BMSMASTER_PCBSTHERM7TEMP_BMSMASTER_PCB7THERM7TEMP_NAME "BMSMaster_PCB7Therm7Temp"
#define BMSMASTER_PCBSTHERM8TEMP_BMSMASTER_PCB1THERM8TEMP_NAME "BMSMaster_PCB1Therm8Temp"
#define BMSMASTER_PCBSTHERM8TEMP_BMSMASTER_PCB2THERM8TEMP_NAME "BMSMaster_PCB2Therm8Temp"
#define BMSMASTER_PCBSTHERM8TEMP_BMSMASTER_PCB3THERM8TEMP_NAME "BMSMaster_PCB3Therm8Temp"
#define BMSMASTER_PCBSTHERM8TEMP_BMSMASTER_PCB4THERM8TEMP_NAME "BMSMaster_PCB4Therm8Temp"
#define BMSMASTER_PCBSTHERM8TEMP_BMSMASTER_PCB5THERM8TEMP_NAME "BMSMaster_PCB5Therm8Temp"
#define BMSMASTER_PCBSTHERM8TEMP_BMSMASTER_PCB6THERM8TEMP_NAME "BMSMaster_PCB6Therm8Temp"
#define BMSMASTER_PCBSTHERM8TEMP_BMSMASTER_PCB7THERM8TEMP_NAME "BMSMaster_PCB7Therm8Temp"
#define BMSMASTER_PCBSTHERM9TEMP_BMSMASTER_PCB1THERM9TEMP_NAME "BMSMaster_PCB1Therm9Temp"
#define BMSMASTER_PCBSTHERM9TEMP_BMSMASTER_PCB2THERM9TEMP_NAME "BMSMaster_PCB2Therm9Temp"
#define BMSMASTER_PCBSTHERM9TEMP_BMSMASTER_PCB13HERM9TEMP_NAME "BMSMaster_PCB13herm9Temp"
#define BMSMASTER_PCBSTHERM9TEMP_BMSMASTER_PCB4THERM9TEMP_NAME "BMSMaster_PCB4Therm9Temp"
#define BMSMASTER_PCBSTHERM9TEMP_BMSMASTER_PCB5THERM9TEMP_NAME "BMSMaster_PCB5Therm9Temp"
#define BMSMASTER_PCBSTHERM9TEMP_BMSMASTER_PCB6THERM9TEMP_NAME "BMSMaster_PCB6Therm9Temp"
#define BMSMASTER_PCBSTHERM9TEMP_BMSMASTER_PCB7THERM9TEMP_NAME "BMSMaster_PCB7Therm9Temp"
#define COOLINGBACK_FAN_SPEEDF1_NAME "SpeedF1"
#define COOLINGBACK_FAN_SPEEDF2_NAME "SpeedF2"
#define BMSMASTER_JK_PACK_BMSMASTER_JK_PACKVOLTAGE_NAME "BMSMaster_JK_PackVoltage"
#define BMSMASTER_JK_PACK_BMSMASTER_JK_PACKCURRENT_NAME "BMSMaster_JK_PackCurrent"
#define BMSMASTER_JK_PACK_BMSMASTER_JK_SOC_NAME "BMSMaster_JK_SOC"
#define BMSMASTER_JK_PACK_BMSMASTER_JK_SOH_NAME "BMSMaster_JK_SOH"
#define BMSMASTER_JK_PACK_BMSMASTER_JK_STATUSFLAGS_NAME "BMSMaster_JK_StatusFlags"
#define BMSMASTER_JK_PACK_BMSMASTER_JK_MODEFLAGS_NAME "BMSMaster_JK_ModeFlags"
#define BMSMASTER_JK_CELLS_1_4_BMSMASTER_JK_CELL1_MV_NAME "BMSMaster_JK_Cell1_mV"
#define BMSMASTER_JK_CELLS_1_4_BMSMASTER_JK_CELL2_MV_NAME "BMSMaster_JK_Cell2_mV"
#define BMSMASTER_JK_CELLS_1_4_BMSMASTER_JK_CELL3_MV_NAME "BMSMaster_JK_Cell3_mV"
#define BMSMASTER_JK_CELLS_1_4_BMSMASTER_JK_CELL4_MV_NAME "BMSMaster_JK_Cell4_mV"
#define BMSMASTER_JK_CELLS_5_8_BMSMASTER_JK_CELL5_MV_NAME "BMSMaster_JK_Cell5_mV"
#define BMSMASTER_JK_CELLS_5_8_BMSMASTER_JK_CELL6_MV_NAME "BMSMaster_JK_Cell6_mV"
#define BMSMASTER_JK_CELLS_5_8_BMSMASTER_JK_CELL7_MV_NAME "BMSMaster_JK_Cell7_mV"
#define BMSMASTER_JK_CELLS_5_8_BMSMASTER_JK_CELL8_MV_NAME "BMSMaster_JK_Cell8_mV"
#define BMSMASTER_JK_CELLS_9_12_BMSMASTER_JK_CELL9_MV_NAME "BMSMaster_JK_Cell9_mV"
#define BMSMASTER_JK_CELLS_9_12_BMSMASTER_JK_CELL10_MV_NAME "BMSMaster_JK_Cell10_mV"
#define BMSMASTER_JK_CELLS_9_12_BMSMASTER_JK_CELL11_MV_NAME "BMSMaster_JK_Cell11_mV"
#define BMSMASTER_JK_CELLS_9_12_BMSMASTER_JK_CELL12_MV_NAME "BMSMaster_JK_Cell12_mV"
#define BMSMASTER_JK_CELLS_13_16_BMSMASTER_JK_CELL13_MV_NAME "BMSMaster_JK_Cell13_mV"
#define BMSMASTER_JK_CELLS_13_16_BMSMASTER_JK_CELL14_MV_NAME "BMSMaster_JK_Cell14_mV"
#define BMSMASTER_JK_CELLS_13_16_BMSMASTER_JK_CELL15_MV_NAME "BMSMaster_JK_Cell15_mV"
#define BMSMASTER_JK_CELLS_13_16_BMSMASTER_JK_CELL16_MV_NAME "BMSMaster_JK_Cell16_mV"
#define BMSMASTER_JK_CELLS_17_20_BMSMASTER_JK_CELL17_MV_NAME "BMSMaster_JK_Cell17_mV"
#define BMSMASTER_JK_CELLS_17_20_BMSMASTER_JK_CELL18_MV_NAME "BMSMaster_JK_Cell18_mV"
#define BMSMASTER_JK_CELLS_17_20_BMSMASTER_JK_CELL19_MV_NAME "BMSMaster_JK_Cell19_mV"
#define BMSMASTER_JK_CELLS_17_20_BMSMASTER_JK_CELL20_MV_NAME "BMSMaster_JK_Cell20_mV"
#define BMSMASTER_JK_CELLS_21_BMSMASTER_JK_CELL21_MV_NAME "BMSMaster_JK_Cell21_mV"
#define BMSMASTER_JK_TEMP_BMSMASTER_JK_MOSTEMP_NAME "BMSMaster_JK_MosTemp"
#define BMSMASTER_JK_TEMP_BMSMASTER_JK_BALTEMP_NAME "BMSMaster_JK_BalTemp"
#define BMSMASTER_JK_CYCLESTATS_BMSMASTER_JK_CYCLES_NAME "BMSMaster_JK_Cycles"
#define BMSMASTER_JK_CYCLESTATS_BMSMASTER_JK_CELLCOUNT_NAME "BMSMaster_JK_CellCount"

/**
 * Signals in message BMSMaster_NODE.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_NODE_t {
    /**
     * Error code from csv errors file
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t Error_Code;

    /**
     * Reserved for future use
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t Reserved;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t Severity;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t Node_Execution_Halted;

    /**
     * Blob for error specific data (sensor reading, variable dump, etc. - depeneds of error)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint64_t Error_Specific_Data;
};

/**
 * Signals in message BMSMaster_END.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_END_t {
    /**
     * Dummy signal in empty message.
     */
    uint8_t dummy;
};

/**
 * Signals in message BMSMaster_MasterVoltCurrTemp.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_MasterVoltCurrTemp_t {
    /**
     * Master battery Voltage MSB value which is read by ADC embedded in stm32 core on BMS Masster board
     *
     * Range: 630..870 (63..87 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t BMSMaster_MasterBatteryVoltage;

    /**
     * Master battery Current LSB value which is read by ADC embedded in stm32 core on BMS Masster board. SIGN CONVENTION: positive = discharging, negative = charging.
     *
     * Range: -3000..3000 (-300..300 A)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t BMSMaster_MasterBatteryCurrent;

    /**
     * Master battery Temperature MSB value which is read by ADC embedded in stm32 core on BMS Masster board
     *
     * Range: 0..10000 (0..100 C)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t BMSMaste_MasterBatteryTemperatur;
};

/**
 * Signals in message BMSMaster_PCBsTherm1Temp.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_PCBsTherm1Temp_t {
    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB1Therm1Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB2Therm1Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB3Therm1Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB4Therm1Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB5Therm1Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB6Therm1Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB7Therm1Temp;
};

/**
 * Signals in message BMSMaster_PCBsTherm2Temp.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_PCBsTherm2Temp_t {
    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB1Therm2Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB2Therm2Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB3Therm2Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB4Therm2Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB5Therm2Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB6Therm2Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB7Therm2Temp;
};

/**
 * Signals in message BMSMaster_PCBsTherm3Temp.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_PCBsTherm3Temp_t {
    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB1Therm3Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB2Therm3Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB3Therm3Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB4Therm3Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB5Therm3Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB6Therm3Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB7Therm3Temp;
};

/**
 * Signals in message BMSMaster_PCBsTherm4Temp.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_PCBsTherm4Temp_t {
    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB1Therm4Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB2Therm4Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB3Therm4Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB4Therm4Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB5Therm4Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB6Therm4Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB7Therm4Temp;
};

/**
 * Signals in message BMSMaster_PCBsTherm5Temp.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_PCBsTherm5Temp_t {
    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB1Therm5Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB2Therm5Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB3Therm5Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB4Therm5Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB5Therm5Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB6Therm5Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB7Therm5Temp;
};

/**
 * Signals in message BMSMaster_PCBsTherm6Temp.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_PCBsTherm6Temp_t {
    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB1Therm6Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB2Therm6Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB3Therm6Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB4Therm6Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB5Therm6Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB6Therm6Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB7Therm6Temp;
};

/**
 * Signals in message BMSMaster_PCBsTherm7Temp.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_PCBsTherm7Temp_t {
    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB1Therm7Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB2Therm7Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB3Therm7Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB4Therm7Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB5Therm7Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB6Therm7Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB7Therm7Temp;
};

/**
 * Signals in message BMSMaster_PCBsTherm8Temp.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_PCBsTherm8Temp_t {
    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB1Therm8Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB2Therm8Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB3Therm8Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB4Therm8Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB5Therm8Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB6Therm8Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB7Therm8Temp;
};

/**
 * Signals in message BMSMaster_PCBsTherm9Temp.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_PCBsTherm9Temp_t {
    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB1Therm9Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB2Therm9Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB13herm9Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB4Therm9Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB5Therm9Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB6Therm9Temp;

    /**
     * Range: 0..255 (0..100 C)
     * Scale: 0.39216
     * Offset: 0
     */
    uint8_t BMSMaster_PCB7Therm9Temp;
};

/**
 * Signals in message CoolingBack_Fan.
 *
 * All signal values are as on the CAN bus.
 */
struct CoolingBack_Fan_t {
    /**
     * Range: 0..100 (0..100 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t SpeedF1;

    /**
     * Range: 0..100 (0..100 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t SpeedF2;
};

/**
 * Signals in message BMSMaster_JK_Pack.
 *
 * JK pack V/I/SOC/SOH/status from BMS_CAN_Get_JK_PackInfo. Voltage/Current factor 0.01 (raw=mV/10, mA/10). StatusFlags bit6 = JK comm error.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_JK_Pack_t {
    /**
     * Range: 0..10000 (0..100 V)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t BMSMaster_JK_PackVoltage;

    /**
     * Pack current as reported by the JK BMS internal shunt. SIGN CONVENTION: positive = discharging, negative = charging - same as BMSMaster_MasterBatteryCurrent, so the two can be compared directly. Note the JK protocol itself uses the opposite sign; BMS Master negates it before transmitting.
     *
     * Range: -30000..30000 (-300..300 A)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t BMSMaster_JK_PackCurrent;

    /**
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t BMSMaster_JK_SOC;

    /**
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t BMSMaster_JK_SOH;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t BMSMaster_JK_StatusFlags;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t BMSMaster_JK_ModeFlags;
};

/**
 * Signals in message BMSMaster_JK_Cells_1_4.
 *
 * JK cells 1..4 voltages [mV] LE u16 from BMS_CAN_Get_JK_CellVolt_1_4.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_JK_Cells_1_4_t {
    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell1_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell2_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell3_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell4_mV;
};

/**
 * Signals in message BMSMaster_JK_Cells_5_8.
 *
 * JK cells 5..8 voltages [mV] LE u16 from BMS_CAN_Get_JK_CellVolt_5_8.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_JK_Cells_5_8_t {
    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell5_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell6_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell7_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell8_mV;
};

/**
 * Signals in message BMSMaster_JK_Cells_9_12.
 *
 * JK cells 9..12 voltages [mV] LE u16 from BMS_CAN_Get_JK_CellVolt_9_12.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_JK_Cells_9_12_t {
    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell9_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell10_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell11_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell12_mV;
};

/**
 * Signals in message BMSMaster_JK_Cells_13_16.
 *
 * JK cells 13..16 voltages [mV] LE u16.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_JK_Cells_13_16_t {
    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell13_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell14_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell15_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell16_mV;
};

/**
 * Signals in message BMSMaster_JK_Cells_17_20.
 *
 * JK cells 17..20 voltages [mV] LE u16.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_JK_Cells_17_20_t {
    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell17_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell18_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell19_mV;

    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell20_mV;
};

/**
 * Signals in message BMSMaster_JK_Cells_21.
 *
 * JK cell 21 voltage [mV] LE u16. Pack is 21S; DLC 2.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_JK_Cells_21_t {
    /**
     * Range: 0..5000 (0..5000 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cell21_mV;
};

/**
 * Signals in message BMSMaster_JK_Temp.
 *
 * JK MOS/balancer temperatures [degC] int8 from BMS_CAN_Get_JK_Temp.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_JK_Temp_t {
    /**
     * Range: -40..125 (-40..125 C)
     * Scale: 1
     * Offset: 0
     */
    int8_t BMSMaster_JK_MosTemp;

    /**
     * Range: -40..125 (-40..125 C)
     * Scale: 1
     * Offset: 0
     */
    int8_t BMSMaster_JK_BalTemp;
};

/**
 * Signals in message BMSMaster_JK_CycleStats.
 *
 * JK cycle count + cellCount from BMS_CAN_Get_JK_CycleStats.
 *
 * All signal values are as on the CAN bus.
 */
struct BMSMaster_JK_CycleStats_t {
    /**
     * Range: 0..65535 (0..65535 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t BMSMaster_JK_Cycles;

    /**
     * Range: 0..32 (0..32 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t BMSMaster_JK_CellCount;
};

/**
 * Pack message BMSMaster_NODE.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_NODE_pack(
    uint8_t *dst_p,
    const struct BMSMaster_NODE_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_NODE.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_NODE_init(struct BMSMaster_NODE_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_NODE_Error_Code_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_NODE_Error_Code_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_NODE_Reserved_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_NODE_Reserved_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_NODE_Severity_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_NODE_Severity_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_NODE_Node_Execution_Halted_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_NODE_Node_Execution_Halted_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t BMSMaster_NODE_Error_Specific_Data_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_NODE_Error_Specific_Data_is_in_range(uint64_t value);

/**
 * Pack message BMSMaster_END.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_END_pack(
    uint8_t *dst_p,
    const struct BMSMaster_END_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_END.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_END_init(struct BMSMaster_END_t *msg_p);

/**
 * Pack message BMSMaster_MasterVoltCurrTemp.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_MasterVoltCurrTemp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_MasterVoltCurrTemp_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_MasterVoltCurrTemp.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_MasterVoltCurrTemp_init(struct BMSMaster_MasterVoltCurrTemp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_MasterVoltCurrTemp_BMSMaster_MasterBatteryVoltage_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_MasterVoltCurrTemp_BMSMaster_MasterBatteryVoltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t BMSMaster_MasterVoltCurrTemp_BMSMaster_MasterBatteryCurrent_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_MasterVoltCurrTemp_BMSMaster_MasterBatteryCurrent_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_MasterVoltCurrTemp_BMSMaste_MasterBatteryTemperatur_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_MasterVoltCurrTemp_BMSMaste_MasterBatteryTemperatur_is_in_range(uint16_t value);

/**
 * Pack message BMSMaster_PCBsTherm1Temp.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_PCBsTherm1Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm1Temp_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_PCBsTherm1Temp.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_PCBsTherm1Temp_init(struct BMSMaster_PCBsTherm1Temp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB1Therm1Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB1Therm1Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB2Therm1Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB2Therm1Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB3Therm1Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB3Therm1Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB4Therm1Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB4Therm1Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB5Therm1Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB5Therm1Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB6Therm1Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB6Therm1Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB7Therm1Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB7Therm1Temp_is_in_range(uint8_t value);

/**
 * Pack message BMSMaster_PCBsTherm2Temp.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_PCBsTherm2Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm2Temp_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_PCBsTherm2Temp.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_PCBsTherm2Temp_init(struct BMSMaster_PCBsTherm2Temp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB1Therm2Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB1Therm2Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB2Therm2Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB2Therm2Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB3Therm2Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB3Therm2Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB4Therm2Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB4Therm2Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB5Therm2Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB5Therm2Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB6Therm2Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB6Therm2Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB7Therm2Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB7Therm2Temp_is_in_range(uint8_t value);

/**
 * Pack message BMSMaster_PCBsTherm3Temp.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_PCBsTherm3Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm3Temp_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_PCBsTherm3Temp.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_PCBsTherm3Temp_init(struct BMSMaster_PCBsTherm3Temp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB1Therm3Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB1Therm3Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB2Therm3Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB2Therm3Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB3Therm3Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB3Therm3Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB4Therm3Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB4Therm3Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB5Therm3Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB5Therm3Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB6Therm3Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB6Therm3Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB7Therm3Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB7Therm3Temp_is_in_range(uint8_t value);

/**
 * Pack message BMSMaster_PCBsTherm4Temp.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_PCBsTherm4Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm4Temp_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_PCBsTherm4Temp.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_PCBsTherm4Temp_init(struct BMSMaster_PCBsTherm4Temp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB1Therm4Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB1Therm4Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB2Therm4Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB2Therm4Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB3Therm4Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB3Therm4Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB4Therm4Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB4Therm4Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB5Therm4Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB5Therm4Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB6Therm4Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB6Therm4Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB7Therm4Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB7Therm4Temp_is_in_range(uint8_t value);

/**
 * Pack message BMSMaster_PCBsTherm5Temp.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_PCBsTherm5Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm5Temp_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_PCBsTherm5Temp.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_PCBsTherm5Temp_init(struct BMSMaster_PCBsTherm5Temp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB1Therm5Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB1Therm5Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB2Therm5Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB2Therm5Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB3Therm5Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB3Therm5Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB4Therm5Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB4Therm5Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB5Therm5Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB5Therm5Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB6Therm5Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB6Therm5Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB7Therm5Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB7Therm5Temp_is_in_range(uint8_t value);

/**
 * Pack message BMSMaster_PCBsTherm6Temp.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_PCBsTherm6Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm6Temp_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_PCBsTherm6Temp.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_PCBsTherm6Temp_init(struct BMSMaster_PCBsTherm6Temp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB1Therm6Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB1Therm6Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB2Therm6Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB2Therm6Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB3Therm6Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB3Therm6Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB4Therm6Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB4Therm6Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB5Therm6Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB5Therm6Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB6Therm6Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB6Therm6Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB7Therm6Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB7Therm6Temp_is_in_range(uint8_t value);

/**
 * Pack message BMSMaster_PCBsTherm7Temp.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_PCBsTherm7Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm7Temp_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_PCBsTherm7Temp.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_PCBsTherm7Temp_init(struct BMSMaster_PCBsTherm7Temp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB1Therm7Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB1Therm7Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB2Therm7Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB2Therm7Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB3Therm7Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB3Therm7Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB4Therm7Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB4Therm7Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB5Therm7Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB5Therm7Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB6Therm7Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB6Therm7Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB7Therm7Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB7Therm7Temp_is_in_range(uint8_t value);

/**
 * Pack message BMSMaster_PCBsTherm8Temp.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_PCBsTherm8Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm8Temp_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_PCBsTherm8Temp.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_PCBsTherm8Temp_init(struct BMSMaster_PCBsTherm8Temp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB1Therm8Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB1Therm8Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB2Therm8Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB2Therm8Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB3Therm8Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB3Therm8Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB4Therm8Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB4Therm8Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB5Therm8Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB5Therm8Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB6Therm8Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB6Therm8Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB7Therm8Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB7Therm8Temp_is_in_range(uint8_t value);

/**
 * Pack message BMSMaster_PCBsTherm9Temp.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_PCBsTherm9Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm9Temp_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_PCBsTherm9Temp.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_PCBsTherm9Temp_init(struct BMSMaster_PCBsTherm9Temp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB1Therm9Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB1Therm9Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB2Therm9Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB2Therm9Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB13herm9Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB13herm9Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB4Therm9Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB4Therm9Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB5Therm9Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB5Therm9Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB6Therm9Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB6Therm9Temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB7Therm9Temp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB7Therm9Temp_is_in_range(uint8_t value);

/**
 * Unpack message CoolingBack_Fan.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int CoolingBack_Fan_unpack(
    struct CoolingBack_Fan_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from CoolingBack_Fan.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int CoolingBack_Fan_init(struct CoolingBack_Fan_t *msg_p);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double CoolingBack_Fan_SpeedF1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool CoolingBack_Fan_SpeedF1_is_in_range(uint8_t value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double CoolingBack_Fan_SpeedF2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool CoolingBack_Fan_SpeedF2_is_in_range(uint8_t value);

/**
 * Pack message BMSMaster_JK_Pack.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_JK_Pack_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Pack_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_JK_Pack.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_JK_Pack_init(struct BMSMaster_JK_Pack_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Pack_BMSMaster_JK_PackVoltage_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Pack_BMSMaster_JK_PackVoltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t BMSMaster_JK_Pack_BMSMaster_JK_PackCurrent_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Pack_BMSMaster_JK_PackCurrent_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_JK_Pack_BMSMaster_JK_SOC_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Pack_BMSMaster_JK_SOC_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_JK_Pack_BMSMaster_JK_SOH_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Pack_BMSMaster_JK_SOH_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_JK_Pack_BMSMaster_JK_StatusFlags_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Pack_BMSMaster_JK_StatusFlags_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_JK_Pack_BMSMaster_JK_ModeFlags_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Pack_BMSMaster_JK_ModeFlags_is_in_range(uint8_t value);

/**
 * Pack message BMSMaster_JK_Cells_1_4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_JK_Cells_1_4_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Cells_1_4_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_JK_Cells_1_4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_JK_Cells_1_4_init(struct BMSMaster_JK_Cells_1_4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell1_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell1_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell2_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell2_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell3_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell3_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell4_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell4_mV_is_in_range(uint16_t value);

/**
 * Pack message BMSMaster_JK_Cells_5_8.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_JK_Cells_5_8_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Cells_5_8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_JK_Cells_5_8.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_JK_Cells_5_8_init(struct BMSMaster_JK_Cells_5_8_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell5_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell5_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell6_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell6_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell7_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell7_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell8_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell8_mV_is_in_range(uint16_t value);

/**
 * Pack message BMSMaster_JK_Cells_9_12.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_JK_Cells_9_12_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Cells_9_12_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_JK_Cells_9_12.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_JK_Cells_9_12_init(struct BMSMaster_JK_Cells_9_12_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell9_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell9_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell10_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell10_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell11_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell11_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell12_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell12_mV_is_in_range(uint16_t value);

/**
 * Pack message BMSMaster_JK_Cells_13_16.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_JK_Cells_13_16_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Cells_13_16_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_JK_Cells_13_16.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_JK_Cells_13_16_init(struct BMSMaster_JK_Cells_13_16_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell13_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell13_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell14_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell14_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell15_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell15_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell16_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell16_mV_is_in_range(uint16_t value);

/**
 * Pack message BMSMaster_JK_Cells_17_20.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_JK_Cells_17_20_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Cells_17_20_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_JK_Cells_17_20.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_JK_Cells_17_20_init(struct BMSMaster_JK_Cells_17_20_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell17_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell17_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell18_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell18_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell19_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell19_mV_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell20_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell20_mV_is_in_range(uint16_t value);

/**
 * Pack message BMSMaster_JK_Cells_21.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_JK_Cells_21_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Cells_21_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_JK_Cells_21.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_JK_Cells_21_init(struct BMSMaster_JK_Cells_21_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_Cells_21_BMSMaster_JK_Cell21_mV_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Cells_21_BMSMaster_JK_Cell21_mV_is_in_range(uint16_t value);

/**
 * Pack message BMSMaster_JK_Temp.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_JK_Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Temp_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_JK_Temp.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_JK_Temp_init(struct BMSMaster_JK_Temp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t BMSMaster_JK_Temp_BMSMaster_JK_MosTemp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Temp_BMSMaster_JK_MosTemp_is_in_range(int8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t BMSMaster_JK_Temp_BMSMaster_JK_BalTemp_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_Temp_BMSMaster_JK_BalTemp_is_in_range(int8_t value);

/**
 * Pack message BMSMaster_JK_CycleStats.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int BMSMaster_JK_CycleStats_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_CycleStats_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMSMaster_JK_CycleStats.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int BMSMaster_JK_CycleStats_init(struct BMSMaster_JK_CycleStats_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t BMSMaster_JK_CycleStats_BMSMaster_JK_Cycles_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_CycleStats_BMSMaster_JK_Cycles_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t BMSMaster_JK_CycleStats_BMSMaster_JK_CellCount_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool BMSMaster_JK_CycleStats_BMSMaster_JK_CellCount_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
