/**
 * @file CAN2_DB.c
 *
 * @brief This source file was generated by cantools version 0.1.dev1949+g29b75602e.d20260911 Sat Sep 12 14:48:26 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "CAN2_DB.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int PCBCells1_NODE_pack(
    uint8_t *dst_p,
    const struct PCBCells1_NODE_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->Error_Code, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->Error_Code, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->Reserved, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->Severity, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u8(src_p->Node_Execution_Halted, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u64(src_p->Error_Specific_Data, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->Error_Specific_Data, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->Error_Specific_Data, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->Error_Specific_Data, 24u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->Error_Specific_Data, 32u, 0xffu);

    return (8);
}

int PCBCells1_NODE_unpack(
    struct PCBCells1_NODE_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->Error_Code = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->Error_Code |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->Reserved = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->Severity = unpack_right_shift_u8(src_p[2], 4u, 0x70u);
    dst_p->Node_Execution_Halted = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->Error_Specific_Data = unpack_right_shift_u64(src_p[3], 0u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[4], 8u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[6], 24u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[7], 32u, 0xffu);

    return (0);
}

int PCBCells1_NODE_init(struct PCBCells1_NODE_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells1_NODE_t));

    return 0;
}

uint16_t PCBCells1_NODE_Error_Code_encode(double value)
{
    return (uint16_t)(value);
}

double PCBCells1_NODE_Error_Code_decode(uint16_t value)
{
    return ((double)value);
}

bool PCBCells1_NODE_Error_Code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t PCBCells1_NODE_Reserved_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells1_NODE_Reserved_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells1_NODE_Reserved_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t PCBCells1_NODE_Severity_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells1_NODE_Severity_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells1_NODE_Severity_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t PCBCells1_NODE_Node_Execution_Halted_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells1_NODE_Node_Execution_Halted_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells1_NODE_Node_Execution_Halted_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint64_t PCBCells1_NODE_Error_Specific_Data_encode(double value)
{
    return (uint64_t)(value);
}

double PCBCells1_NODE_Error_Specific_Data_decode(uint64_t value)
{
    return ((double)value);
}

bool PCBCells1_NODE_Error_Specific_Data_is_in_range(uint64_t value)
{
    return (value <= 1099511627775ull);
}

int PCBCells2_NODE_pack(
    uint8_t *dst_p,
    const struct PCBCells2_NODE_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->Error_Code, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->Error_Code, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->Reserved, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->Severity, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u8(src_p->Nde_Execution_Halted, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u64(src_p->Error_Specific_Data, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->Error_Specific_Data, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->Error_Specific_Data, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->Error_Specific_Data, 24u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->Error_Specific_Data, 32u, 0xffu);

    return (8);
}

int PCBCells2_NODE_unpack(
    struct PCBCells2_NODE_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->Error_Code = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->Error_Code |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->Reserved = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->Severity = unpack_right_shift_u8(src_p[2], 4u, 0x70u);
    dst_p->Nde_Execution_Halted = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->Error_Specific_Data = unpack_right_shift_u64(src_p[3], 0u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[4], 8u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[6], 24u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[7], 32u, 0xffu);

    return (0);
}

int PCBCells2_NODE_init(struct PCBCells2_NODE_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells2_NODE_t));

    return 0;
}

uint16_t PCBCells2_NODE_Error_Code_encode(double value)
{
    return (uint16_t)(value);
}

double PCBCells2_NODE_Error_Code_decode(uint16_t value)
{
    return ((double)value);
}

bool PCBCells2_NODE_Error_Code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t PCBCells2_NODE_Reserved_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells2_NODE_Reserved_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells2_NODE_Reserved_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t PCBCells2_NODE_Severity_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells2_NODE_Severity_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells2_NODE_Severity_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t PCBCells2_NODE_Nde_Execution_Halted_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells2_NODE_Nde_Execution_Halted_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells2_NODE_Nde_Execution_Halted_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint64_t PCBCells2_NODE_Error_Specific_Data_encode(double value)
{
    return (uint64_t)(value);
}

double PCBCells2_NODE_Error_Specific_Data_decode(uint64_t value)
{
    return ((double)value);
}

bool PCBCells2_NODE_Error_Specific_Data_is_in_range(uint64_t value)
{
    return (value <= 1099511627775ull);
}

int PCBCells3_NODE_pack(
    uint8_t *dst_p,
    const struct PCBCells3_NODE_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->Error_Code, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->Error_Code, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->Reserved, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->Severity, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u8(src_p->Node_Execution_Halted, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u64(src_p->Error_Specific_Data, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->Error_Specific_Data, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->Error_Specific_Data, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->Error_Specific_Data, 24u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->Error_Specific_Data, 32u, 0xffu);

    return (8);
}

int PCBCells3_NODE_unpack(
    struct PCBCells3_NODE_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->Error_Code = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->Error_Code |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->Reserved = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->Severity = unpack_right_shift_u8(src_p[2], 4u, 0x70u);
    dst_p->Node_Execution_Halted = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->Error_Specific_Data = unpack_right_shift_u64(src_p[3], 0u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[4], 8u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[6], 24u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[7], 32u, 0xffu);

    return (0);
}

int PCBCells3_NODE_init(struct PCBCells3_NODE_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells3_NODE_t));

    return 0;
}

uint16_t PCBCells3_NODE_Error_Code_encode(double value)
{
    return (uint16_t)(value);
}

double PCBCells3_NODE_Error_Code_decode(uint16_t value)
{
    return ((double)value);
}

bool PCBCells3_NODE_Error_Code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t PCBCells3_NODE_Reserved_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells3_NODE_Reserved_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells3_NODE_Reserved_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t PCBCells3_NODE_Severity_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells3_NODE_Severity_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells3_NODE_Severity_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t PCBCells3_NODE_Node_Execution_Halted_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells3_NODE_Node_Execution_Halted_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells3_NODE_Node_Execution_Halted_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint64_t PCBCells3_NODE_Error_Specific_Data_encode(double value)
{
    return (uint64_t)(value);
}

double PCBCells3_NODE_Error_Specific_Data_decode(uint64_t value)
{
    return ((double)value);
}

bool PCBCells3_NODE_Error_Specific_Data_is_in_range(uint64_t value)
{
    return (value <= 1099511627775ull);
}

int PCBCells4_NODE_pack(
    uint8_t *dst_p,
    const struct PCBCells4_NODE_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->Error_Code, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->Error_Code, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->Reseerved, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->Severity, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u8(src_p->Node_Execution_Halted, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u64(src_p->Error_Specifid_Data, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->Error_Specifid_Data, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->Error_Specifid_Data, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->Error_Specifid_Data, 24u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->Error_Specifid_Data, 32u, 0xffu);

    return (8);
}

int PCBCells4_NODE_unpack(
    struct PCBCells4_NODE_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->Error_Code = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->Error_Code |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->Reseerved = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->Severity = unpack_right_shift_u8(src_p[2], 4u, 0x70u);
    dst_p->Node_Execution_Halted = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->Error_Specifid_Data = unpack_right_shift_u64(src_p[3], 0u, 0xffu);
    dst_p->Error_Specifid_Data |= unpack_left_shift_u64(src_p[4], 8u, 0xffu);
    dst_p->Error_Specifid_Data |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->Error_Specifid_Data |= unpack_left_shift_u64(src_p[6], 24u, 0xffu);
    dst_p->Error_Specifid_Data |= unpack_left_shift_u64(src_p[7], 32u, 0xffu);

    return (0);
}

int PCBCells4_NODE_init(struct PCBCells4_NODE_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells4_NODE_t));

    return 0;
}

uint16_t PCBCells4_NODE_Error_Code_encode(double value)
{
    return (uint16_t)(value);
}

double PCBCells4_NODE_Error_Code_decode(uint16_t value)
{
    return ((double)value);
}

bool PCBCells4_NODE_Error_Code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t PCBCells4_NODE_Reseerved_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells4_NODE_Reseerved_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells4_NODE_Reseerved_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t PCBCells4_NODE_Severity_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells4_NODE_Severity_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells4_NODE_Severity_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t PCBCells4_NODE_Node_Execution_Halted_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells4_NODE_Node_Execution_Halted_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells4_NODE_Node_Execution_Halted_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint64_t PCBCells4_NODE_Error_Specifid_Data_encode(double value)
{
    return (uint64_t)(value);
}

double PCBCells4_NODE_Error_Specifid_Data_decode(uint64_t value)
{
    return ((double)value);
}

bool PCBCells4_NODE_Error_Specifid_Data_is_in_range(uint64_t value)
{
    return (value <= 1099511627775ull);
}

int PCBCells5_NODE_pack(
    uint8_t *dst_p,
    const struct PCBCells5_NODE_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->Error_Code, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->Error_Code, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->Reserved, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->Severity, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u8(src_p->Node_Execution_Halted, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u64(src_p->Error_Specific_Data, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->Error_Specific_Data, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->Error_Specific_Data, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->Error_Specific_Data, 24u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->Error_Specific_Data, 32u, 0xffu);

    return (8);
}

int PCBCells5_NODE_unpack(
    struct PCBCells5_NODE_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->Error_Code = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->Error_Code |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->Reserved = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->Severity = unpack_right_shift_u8(src_p[2], 4u, 0x70u);
    dst_p->Node_Execution_Halted = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->Error_Specific_Data = unpack_right_shift_u64(src_p[3], 0u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[4], 8u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[6], 24u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[7], 32u, 0xffu);

    return (0);
}

int PCBCells5_NODE_init(struct PCBCells5_NODE_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells5_NODE_t));

    return 0;
}

uint16_t PCBCells5_NODE_Error_Code_encode(double value)
{
    return (uint16_t)(value);
}

double PCBCells5_NODE_Error_Code_decode(uint16_t value)
{
    return ((double)value);
}

bool PCBCells5_NODE_Error_Code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t PCBCells5_NODE_Reserved_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells5_NODE_Reserved_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells5_NODE_Reserved_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t PCBCells5_NODE_Severity_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells5_NODE_Severity_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells5_NODE_Severity_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t PCBCells5_NODE_Node_Execution_Halted_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells5_NODE_Node_Execution_Halted_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells5_NODE_Node_Execution_Halted_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint64_t PCBCells5_NODE_Error_Specific_Data_encode(double value)
{
    return (uint64_t)(value);
}

double PCBCells5_NODE_Error_Specific_Data_decode(uint64_t value)
{
    return ((double)value);
}

bool PCBCells5_NODE_Error_Specific_Data_is_in_range(uint64_t value)
{
    return (value <= 1099511627775ull);
}

int PCBCells6_NODE_pack(
    uint8_t *dst_p,
    const struct PCBCells6_NODE_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->Error_Code, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->Error_Code, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->Reserved, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->Severity, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u8(src_p->Node_Execution_Halted, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u64(src_p->Error_Specific_Data, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->Error_Specific_Data, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->Error_Specific_Data, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->Error_Specific_Data, 24u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->Error_Specific_Data, 32u, 0xffu);

    return (8);
}

int PCBCells6_NODE_unpack(
    struct PCBCells6_NODE_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->Error_Code = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->Error_Code |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->Reserved = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->Severity = unpack_right_shift_u8(src_p[2], 4u, 0x70u);
    dst_p->Node_Execution_Halted = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->Error_Specific_Data = unpack_right_shift_u64(src_p[3], 0u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[4], 8u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[6], 24u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[7], 32u, 0xffu);

    return (0);
}

int PCBCells6_NODE_init(struct PCBCells6_NODE_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells6_NODE_t));

    return 0;
}

uint16_t PCBCells6_NODE_Error_Code_encode(double value)
{
    return (uint16_t)(value);
}

double PCBCells6_NODE_Error_Code_decode(uint16_t value)
{
    return ((double)value);
}

bool PCBCells6_NODE_Error_Code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t PCBCells6_NODE_Reserved_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells6_NODE_Reserved_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells6_NODE_Reserved_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t PCBCells6_NODE_Severity_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells6_NODE_Severity_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells6_NODE_Severity_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t PCBCells6_NODE_Node_Execution_Halted_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells6_NODE_Node_Execution_Halted_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells6_NODE_Node_Execution_Halted_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint64_t PCBCells6_NODE_Error_Specific_Data_encode(double value)
{
    return (uint64_t)(value);
}

double PCBCells6_NODE_Error_Specific_Data_decode(uint64_t value)
{
    return ((double)value);
}

bool PCBCells6_NODE_Error_Specific_Data_is_in_range(uint64_t value)
{
    return (value <= 1099511627775ull);
}

int PCBCells7_NODE_pack(
    uint8_t *dst_p,
    const struct PCBCells7_NODE_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->Error_Code, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->Error_Code, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->Reserved, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->Severity, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u8(src_p->Node_Execution_Halted, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u64(src_p->Error_Specific_Data, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->Error_Specific_Data, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->Error_Specific_Data, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->Error_Specific_Data, 24u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->Error_Specific_Data, 32u, 0xffu);

    return (8);
}

int PCBCells7_NODE_unpack(
    struct PCBCells7_NODE_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->Error_Code = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->Error_Code |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->Reserved = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->Severity = unpack_right_shift_u8(src_p[2], 4u, 0x70u);
    dst_p->Node_Execution_Halted = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->Error_Specific_Data = unpack_right_shift_u64(src_p[3], 0u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[4], 8u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[6], 24u, 0xffu);
    dst_p->Error_Specific_Data |= unpack_left_shift_u64(src_p[7], 32u, 0xffu);

    return (0);
}

int PCBCells7_NODE_init(struct PCBCells7_NODE_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells7_NODE_t));

    return 0;
}

uint16_t PCBCells7_NODE_Error_Code_encode(double value)
{
    return (uint16_t)(value);
}

double PCBCells7_NODE_Error_Code_decode(uint16_t value)
{
    return ((double)value);
}

bool PCBCells7_NODE_Error_Code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t PCBCells7_NODE_Reserved_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells7_NODE_Reserved_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells7_NODE_Reserved_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t PCBCells7_NODE_Severity_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells7_NODE_Severity_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells7_NODE_Severity_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t PCBCells7_NODE_Node_Execution_Halted_encode(double value)
{
    return (uint8_t)(value);
}

double PCBCells7_NODE_Node_Execution_Halted_decode(uint8_t value)
{
    return ((double)value);
}

bool PCBCells7_NODE_Node_Execution_Halted_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint64_t PCBCells7_NODE_Error_Specific_Data_encode(double value)
{
    return (uint64_t)(value);
}

double PCBCells7_NODE_Error_Specific_Data_decode(uint64_t value)
{
    return ((double)value);
}

bool PCBCells7_NODE_Error_Specific_Data_is_in_range(uint64_t value)
{
    return (value <= 1099511627775ull);
}

int PCBCells1_Therm1_pack(
    uint8_t *dst_p,
    const struct PCBCells1_Therm1_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells1_Therm1_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells1_Therm1_unpack(
    struct PCBCells1_Therm1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells1_Therm1_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells1_Therm1_init(struct PCBCells1_Therm1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells1_Therm1_t));

    return 0;
}

uint8_t PCBCells1_Therm1_PCBCells1_Therm1_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells1_Therm1_PCBCells1_Therm1_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells1_Therm1_PCBCells1_Therm1_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells1_Therm2_pack(
    uint8_t *dst_p,
    const struct PCBCells1_Therm2_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells1_Therm2_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells1_Therm2_unpack(
    struct PCBCells1_Therm2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells1_Therm2_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells1_Therm2_init(struct PCBCells1_Therm2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells1_Therm2_t));

    return 0;
}

uint8_t PCBCells1_Therm2_PCBCells1_Therm2_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells1_Therm2_PCBCells1_Therm2_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells1_Therm2_PCBCells1_Therm2_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells1_Therm3_pack(
    uint8_t *dst_p,
    const struct PCBCells1_Therm3_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells1_Therm3_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells1_Therm3_unpack(
    struct PCBCells1_Therm3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells1_Therm3_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells1_Therm3_init(struct PCBCells1_Therm3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells1_Therm3_t));

    return 0;
}

uint8_t PCBCells1_Therm3_PCBCells1_Therm3_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells1_Therm3_PCBCells1_Therm3_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells1_Therm3_PCBCells1_Therm3_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells1_Therm4_pack(
    uint8_t *dst_p,
    const struct PCBCells1_Therm4_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells1_Therm4_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells1_Therm4_unpack(
    struct PCBCells1_Therm4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells1_Therm4_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells1_Therm4_init(struct PCBCells1_Therm4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells1_Therm4_t));

    return 0;
}

uint8_t PCBCells1_Therm4_PCBCells1_Therm4_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells1_Therm4_PCBCells1_Therm4_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells1_Therm4_PCBCells1_Therm4_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells1_Therm5_pack(
    uint8_t *dst_p,
    const struct PCBCells1_Therm5_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells1_Therm5_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells1_Therm5_unpack(
    struct PCBCells1_Therm5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells1_Therm5_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells1_Therm5_init(struct PCBCells1_Therm5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells1_Therm5_t));

    return 0;
}

uint8_t PCBCells1_Therm5_PCBCells1_Therm5_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells1_Therm5_PCBCells1_Therm5_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells1_Therm5_PCBCells1_Therm5_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells1_Therm6_pack(
    uint8_t *dst_p,
    const struct PCBCells1_Therm6_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells1_Therm6_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells1_Therm6_unpack(
    struct PCBCells1_Therm6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells1_Therm6_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells1_Therm6_init(struct PCBCells1_Therm6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells1_Therm6_t));

    return 0;
}

uint8_t PCBCells1_Therm6_PCBCells1_Therm6_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells1_Therm6_PCBCells1_Therm6_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells1_Therm6_PCBCells1_Therm6_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells1_Therm7_pack(
    uint8_t *dst_p,
    const struct PCBCells1_Therm7_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells1_Therm7_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells1_Therm7_unpack(
    struct PCBCells1_Therm7_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells1_Therm7_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells1_Therm7_init(struct PCBCells1_Therm7_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells1_Therm7_t));

    return 0;
}

uint8_t PCBCells1_Therm7_PCBCells1_Therm7_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells1_Therm7_PCBCells1_Therm7_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells1_Therm7_PCBCells1_Therm7_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells1_Therm8_pack(
    uint8_t *dst_p,
    const struct PCBCells1_Therm8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells1_Therm8_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells1_Therm8_unpack(
    struct PCBCells1_Therm8_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells1_Therm8_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells1_Therm8_init(struct PCBCells1_Therm8_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells1_Therm8_t));

    return 0;
}

uint8_t PCBCells1_Therm8_PCBCells1_Therm8_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells1_Therm8_PCBCells1_Therm8_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells1_Therm8_PCBCells1_Therm8_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells1_Therm9_pack(
    uint8_t *dst_p,
    const struct PCBCells1_Therm9_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells1_Therm9_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells1_Therm9_unpack(
    struct PCBCells1_Therm9_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells1_Therm9_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells1_Therm9_init(struct PCBCells1_Therm9_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells1_Therm9_t));

    return 0;
}

uint8_t PCBCells1_Therm9_PCBCells1_Therm9_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells1_Therm9_PCBCells1_Therm9_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells1_Therm9_PCBCells1_Therm9_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells2_Therm9_pack(
    uint8_t *dst_p,
    const struct PCBCells2_Therm9_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells2_Therm9_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells2_Therm9_unpack(
    struct PCBCells2_Therm9_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells2_Therm9_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells2_Therm9_init(struct PCBCells2_Therm9_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells2_Therm9_t));

    return 0;
}

uint8_t PCBCells2_Therm9_PCBCells2_Therm9_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells2_Therm9_PCBCells2_Therm9_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells2_Therm9_PCBCells2_Therm9_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells2_Therm8_pack(
    uint8_t *dst_p,
    const struct PCBCells2_Therm8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells2_Therm8_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells2_Therm8_unpack(
    struct PCBCells2_Therm8_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells2_Therm8_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells2_Therm8_init(struct PCBCells2_Therm8_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells2_Therm8_t));

    return 0;
}

uint8_t PCBCells2_Therm8_PCBCells2_Therm8_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells2_Therm8_PCBCells2_Therm8_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells2_Therm8_PCBCells2_Therm8_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells2_Therm7_pack(
    uint8_t *dst_p,
    const struct PCBCells2_Therm7_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells2_Therm7_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells2_Therm7_unpack(
    struct PCBCells2_Therm7_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells2_Therm7_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells2_Therm7_init(struct PCBCells2_Therm7_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells2_Therm7_t));

    return 0;
}

uint8_t PCBCells2_Therm7_PCBCells2_Therm7_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells2_Therm7_PCBCells2_Therm7_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells2_Therm7_PCBCells2_Therm7_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells2_Therm6_pack(
    uint8_t *dst_p,
    const struct PCBCells2_Therm6_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells2_Therm6_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells2_Therm6_unpack(
    struct PCBCells2_Therm6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells2_Therm6_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells2_Therm6_init(struct PCBCells2_Therm6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells2_Therm6_t));

    return 0;
}

uint8_t PCBCells2_Therm6_PCBCells2_Therm6_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells2_Therm6_PCBCells2_Therm6_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells2_Therm6_PCBCells2_Therm6_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells2_Therm5_pack(
    uint8_t *dst_p,
    const struct PCBCells2_Therm5_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells2_Therm5_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells2_Therm5_unpack(
    struct PCBCells2_Therm5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells2_Therm5_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells2_Therm5_init(struct PCBCells2_Therm5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells2_Therm5_t));

    return 0;
}

uint8_t PCBCells2_Therm5_PCBCells2_Therm5_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells2_Therm5_PCBCells2_Therm5_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells2_Therm5_PCBCells2_Therm5_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells2_Therm4_pack(
    uint8_t *dst_p,
    const struct PCBCells2_Therm4_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells2_Therm4_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells2_Therm4_unpack(
    struct PCBCells2_Therm4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells2_Therm4_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells2_Therm4_init(struct PCBCells2_Therm4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells2_Therm4_t));

    return 0;
}

uint8_t PCBCells2_Therm4_PCBCells2_Therm4_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells2_Therm4_PCBCells2_Therm4_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells2_Therm4_PCBCells2_Therm4_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells2_Therm3_pack(
    uint8_t *dst_p,
    const struct PCBCells2_Therm3_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells2_Therm3_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells2_Therm3_unpack(
    struct PCBCells2_Therm3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells2_Therm3_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells2_Therm3_init(struct PCBCells2_Therm3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells2_Therm3_t));

    return 0;
}

uint8_t PCBCells2_Therm3_PCBCells2_Therm3_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells2_Therm3_PCBCells2_Therm3_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells2_Therm3_PCBCells2_Therm3_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells2_Therm2_pack(
    uint8_t *dst_p,
    const struct PCBCells2_Therm2_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells2_Therm2_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells2_Therm2_unpack(
    struct PCBCells2_Therm2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells2_Therm2_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells2_Therm2_init(struct PCBCells2_Therm2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells2_Therm2_t));

    return 0;
}

uint8_t PCBCells2_Therm2_PCBCells2_Therm2_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells2_Therm2_PCBCells2_Therm2_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells2_Therm2_PCBCells2_Therm2_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells2_Therm1_pack(
    uint8_t *dst_p,
    const struct PCBCells2_Therm1_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells2_Therm1_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells2_Therm1_unpack(
    struct PCBCells2_Therm1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells2_Therm1_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells2_Therm1_init(struct PCBCells2_Therm1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells2_Therm1_t));

    return 0;
}

uint8_t PCBCells2_Therm1_PCBCells2_Therm1_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells2_Therm1_PCBCells2_Therm1_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells2_Therm1_PCBCells2_Therm1_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells3_Therm1_pack(
    uint8_t *dst_p,
    const struct PCBCells3_Therm1_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells3_Therm1_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells3_Therm1_unpack(
    struct PCBCells3_Therm1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells3_Therm1_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells3_Therm1_init(struct PCBCells3_Therm1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells3_Therm1_t));

    return 0;
}

uint8_t PCBCells3_Therm1_PCBCells3_Therm1_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells3_Therm1_PCBCells3_Therm1_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells3_Therm1_PCBCells3_Therm1_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells3_Therm2_pack(
    uint8_t *dst_p,
    const struct PCBCells3_Therm2_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells3_Therm2_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells3_Therm2_unpack(
    struct PCBCells3_Therm2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells3_Therm2_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells3_Therm2_init(struct PCBCells3_Therm2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells3_Therm2_t));

    return 0;
}

uint8_t PCBCells3_Therm2_PCBCells3_Therm2_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells3_Therm2_PCBCells3_Therm2_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells3_Therm2_PCBCells3_Therm2_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells3_Therm3_pack(
    uint8_t *dst_p,
    const struct PCBCells3_Therm3_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells3_Therm3_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells3_Therm3_unpack(
    struct PCBCells3_Therm3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells3_Therm3_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells3_Therm3_init(struct PCBCells3_Therm3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells3_Therm3_t));

    return 0;
}

uint8_t PCBCells3_Therm3_PCBCells3_Therm3_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells3_Therm3_PCBCells3_Therm3_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells3_Therm3_PCBCells3_Therm3_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells3_Therm4_pack(
    uint8_t *dst_p,
    const struct PCBCells3_Therm4_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells3_Therm4_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells3_Therm4_unpack(
    struct PCBCells3_Therm4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells3_Therm4_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells3_Therm4_init(struct PCBCells3_Therm4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells3_Therm4_t));

    return 0;
}

uint8_t PCBCells3_Therm4_PCBCells3_Therm4_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells3_Therm4_PCBCells3_Therm4_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells3_Therm4_PCBCells3_Therm4_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells3_Therm5_pack(
    uint8_t *dst_p,
    const struct PCBCells3_Therm5_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells3_Therm5_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells3_Therm5_unpack(
    struct PCBCells3_Therm5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells3_Therm5_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells3_Therm5_init(struct PCBCells3_Therm5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells3_Therm5_t));

    return 0;
}

uint8_t PCBCells3_Therm5_PCBCells3_Therm5_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells3_Therm5_PCBCells3_Therm5_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells3_Therm5_PCBCells3_Therm5_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells3_Therm6_pack(
    uint8_t *dst_p,
    const struct PCBCells3_Therm6_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells3_Therm6_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells3_Therm6_unpack(
    struct PCBCells3_Therm6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells3_Therm6_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells3_Therm6_init(struct PCBCells3_Therm6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells3_Therm6_t));

    return 0;
}

uint8_t PCBCells3_Therm6_PCBCells3_Therm6_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells3_Therm6_PCBCells3_Therm6_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells3_Therm6_PCBCells3_Therm6_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells3_Therm7_pack(
    uint8_t *dst_p,
    const struct PCBCells3_Therm7_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells3_Therm7_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells3_Therm7_unpack(
    struct PCBCells3_Therm7_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells3_Therm7_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells3_Therm7_init(struct PCBCells3_Therm7_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells3_Therm7_t));

    return 0;
}

uint8_t PCBCells3_Therm7_PCBCells3_Therm7_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells3_Therm7_PCBCells3_Therm7_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells3_Therm7_PCBCells3_Therm7_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells3_Therm8_pack(
    uint8_t *dst_p,
    const struct PCBCells3_Therm8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells3_Therm8_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells3_Therm8_unpack(
    struct PCBCells3_Therm8_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells3_Therm8_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells3_Therm8_init(struct PCBCells3_Therm8_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells3_Therm8_t));

    return 0;
}

uint8_t PCBCells3_Therm8_PCBCells3_Therm8_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells3_Therm8_PCBCells3_Therm8_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells3_Therm8_PCBCells3_Therm8_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells3_Therm9_pack(
    uint8_t *dst_p,
    const struct PCBCells3_Therm9_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells3_Therm9_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells3_Therm9_unpack(
    struct PCBCells3_Therm9_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells3_Therm9_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells3_Therm9_init(struct PCBCells3_Therm9_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells3_Therm9_t));

    return 0;
}

uint8_t PCBCells3_Therm9_PCBCells3_Therm9_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells3_Therm9_PCBCells3_Therm9_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells3_Therm9_PCBCells3_Therm9_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells4_Therm9_pack(
    uint8_t *dst_p,
    const struct PCBCells4_Therm9_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells4_Therm9_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells4_Therm9_unpack(
    struct PCBCells4_Therm9_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells4_Therm9_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells4_Therm9_init(struct PCBCells4_Therm9_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells4_Therm9_t));

    return 0;
}

uint8_t PCBCells4_Therm9_PCBCells4_Therm9_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells4_Therm9_PCBCells4_Therm9_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells4_Therm9_PCBCells4_Therm9_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells4_Therm8_pack(
    uint8_t *dst_p,
    const struct PCBCells4_Therm8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells4_Therm8_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells4_Therm8_unpack(
    struct PCBCells4_Therm8_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells4_Therm8_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells4_Therm8_init(struct PCBCells4_Therm8_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells4_Therm8_t));

    return 0;
}

uint8_t PCBCells4_Therm8_PCBCells4_Therm8_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells4_Therm8_PCBCells4_Therm8_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells4_Therm8_PCBCells4_Therm8_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells4_Therm7_pack(
    uint8_t *dst_p,
    const struct PCBCells4_Therm7_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells4_Therm7_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells4_Therm7_unpack(
    struct PCBCells4_Therm7_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells4_Therm7_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells4_Therm7_init(struct PCBCells4_Therm7_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells4_Therm7_t));

    return 0;
}

uint8_t PCBCells4_Therm7_PCBCells4_Therm7_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells4_Therm7_PCBCells4_Therm7_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells4_Therm7_PCBCells4_Therm7_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells4_Therm6_pack(
    uint8_t *dst_p,
    const struct PCBCells4_Therm6_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells4_Therm6_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells4_Therm6_unpack(
    struct PCBCells4_Therm6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells4_Therm6_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells4_Therm6_init(struct PCBCells4_Therm6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells4_Therm6_t));

    return 0;
}

uint8_t PCBCells4_Therm6_PCBCells4_Therm6_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells4_Therm6_PCBCells4_Therm6_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells4_Therm6_PCBCells4_Therm6_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells4_Therm5_pack(
    uint8_t *dst_p,
    const struct PCBCells4_Therm5_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells4_Therm5_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells4_Therm5_unpack(
    struct PCBCells4_Therm5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells4_Therm5_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells4_Therm5_init(struct PCBCells4_Therm5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells4_Therm5_t));

    return 0;
}

uint8_t PCBCells4_Therm5_PCBCells4_Therm5_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells4_Therm5_PCBCells4_Therm5_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells4_Therm5_PCBCells4_Therm5_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells4_Therm4_pack(
    uint8_t *dst_p,
    const struct PCBCells4_Therm4_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells4_Therm4_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells4_Therm4_unpack(
    struct PCBCells4_Therm4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells4_Therm4_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells4_Therm4_init(struct PCBCells4_Therm4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells4_Therm4_t));

    return 0;
}

uint8_t PCBCells4_Therm4_PCBCells4_Therm4_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells4_Therm4_PCBCells4_Therm4_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells4_Therm4_PCBCells4_Therm4_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells4_Therm3_pack(
    uint8_t *dst_p,
    const struct PCBCells4_Therm3_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells4_Therm3_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells4_Therm3_unpack(
    struct PCBCells4_Therm3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells4_Therm3_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells4_Therm3_init(struct PCBCells4_Therm3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells4_Therm3_t));

    return 0;
}

uint8_t PCBCells4_Therm3_PCBCells4_Therm3_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells4_Therm3_PCBCells4_Therm3_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells4_Therm3_PCBCells4_Therm3_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells4_Therm2_pack(
    uint8_t *dst_p,
    const struct PCBCells4_Therm2_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells4_Therm2_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells4_Therm2_unpack(
    struct PCBCells4_Therm2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells4_Therm2_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells4_Therm2_init(struct PCBCells4_Therm2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells4_Therm2_t));

    return 0;
}

uint8_t PCBCells4_Therm2_PCBCells4_Therm2_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells4_Therm2_PCBCells4_Therm2_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells4_Therm2_PCBCells4_Therm2_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells4_Therm1_pack(
    uint8_t *dst_p,
    const struct PCBCells4_Therm1_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells4_Therm1_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells4_Therm1_unpack(
    struct PCBCells4_Therm1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells4_Therm1_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells4_Therm1_init(struct PCBCells4_Therm1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells4_Therm1_t));

    return 0;
}

uint8_t PCBCells4_Therm1_PCBCells4_Therm1_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells4_Therm1_PCBCells4_Therm1_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells4_Therm1_PCBCells4_Therm1_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells5_Therm1_pack(
    uint8_t *dst_p,
    const struct PCBCells5_Therm1_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells5_Therm1_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells5_Therm1_unpack(
    struct PCBCells5_Therm1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells5_Therm1_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells5_Therm1_init(struct PCBCells5_Therm1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells5_Therm1_t));

    return 0;
}

uint8_t PCBCells5_Therm1_PCBCells5_Therm1_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells5_Therm1_PCBCells5_Therm1_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells5_Therm1_PCBCells5_Therm1_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells5_Therm2_pack(
    uint8_t *dst_p,
    const struct PCBCells5_Therm2_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells5_Therm2_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells5_Therm2_unpack(
    struct PCBCells5_Therm2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells5_Therm2_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells5_Therm2_init(struct PCBCells5_Therm2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells5_Therm2_t));

    return 0;
}

uint8_t PCBCells5_Therm2_PCBCells5_Therm2_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells5_Therm2_PCBCells5_Therm2_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells5_Therm2_PCBCells5_Therm2_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells5_Therm3_pack(
    uint8_t *dst_p,
    const struct PCBCells5_Therm3_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells5_Therm3_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells5_Therm3_unpack(
    struct PCBCells5_Therm3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells5_Therm3_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells5_Therm3_init(struct PCBCells5_Therm3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells5_Therm3_t));

    return 0;
}

uint8_t PCBCells5_Therm3_PCBCells5_Therm3_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells5_Therm3_PCBCells5_Therm3_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells5_Therm3_PCBCells5_Therm3_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells5_Therm4_pack(
    uint8_t *dst_p,
    const struct PCBCells5_Therm4_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells5_Therm4_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells5_Therm4_unpack(
    struct PCBCells5_Therm4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells5_Therm4_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells5_Therm4_init(struct PCBCells5_Therm4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells5_Therm4_t));

    return 0;
}

uint8_t PCBCells5_Therm4_PCBCells5_Therm4_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells5_Therm4_PCBCells5_Therm4_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells5_Therm4_PCBCells5_Therm4_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells5_Therm5_pack(
    uint8_t *dst_p,
    const struct PCBCells5_Therm5_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells5_Therm5_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells5_Therm5_unpack(
    struct PCBCells5_Therm5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells5_Therm5_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells5_Therm5_init(struct PCBCells5_Therm5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells5_Therm5_t));

    return 0;
}

uint8_t PCBCells5_Therm5_PCBCells5_Therm5_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells5_Therm5_PCBCells5_Therm5_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells5_Therm5_PCBCells5_Therm5_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells5_Therm6_pack(
    uint8_t *dst_p,
    const struct PCBCells5_Therm6_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells5_Therm6_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells5_Therm6_unpack(
    struct PCBCells5_Therm6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells5_Therm6_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells5_Therm6_init(struct PCBCells5_Therm6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells5_Therm6_t));

    return 0;
}

uint8_t PCBCells5_Therm6_PCBCells5_Therm6_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells5_Therm6_PCBCells5_Therm6_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells5_Therm6_PCBCells5_Therm6_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells5_Therm7_pack(
    uint8_t *dst_p,
    const struct PCBCells5_Therm7_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells5_Therm7_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells5_Therm7_unpack(
    struct PCBCells5_Therm7_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells5_Therm7_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells5_Therm7_init(struct PCBCells5_Therm7_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells5_Therm7_t));

    return 0;
}

uint8_t PCBCells5_Therm7_PCBCells5_Therm7_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells5_Therm7_PCBCells5_Therm7_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells5_Therm7_PCBCells5_Therm7_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells5_Therm8_pack(
    uint8_t *dst_p,
    const struct PCBCells5_Therm8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells5_Therm8_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells5_Therm8_unpack(
    struct PCBCells5_Therm8_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells5_Therm8_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells5_Therm8_init(struct PCBCells5_Therm8_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells5_Therm8_t));

    return 0;
}

uint8_t PCBCells5_Therm8_PCBCells5_Therm8_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells5_Therm8_PCBCells5_Therm8_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells5_Therm8_PCBCells5_Therm8_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells5_Therm9_pack(
    uint8_t *dst_p,
    const struct PCBCells5_Therm9_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells5_Therm9_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells5_Therm9_unpack(
    struct PCBCells5_Therm9_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells5_Therm9_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells5_Therm9_init(struct PCBCells5_Therm9_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells5_Therm9_t));

    return 0;
}

uint8_t PCBCells5_Therm9_PCBCells5_Therm9_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells5_Therm9_PCBCells5_Therm9_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells5_Therm9_PCBCells5_Therm9_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells6_Therm9_pack(
    uint8_t *dst_p,
    const struct PCBCells6_Therm9_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells6_Therm9_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells6_Therm9_unpack(
    struct PCBCells6_Therm9_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells6_Therm9_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells6_Therm9_init(struct PCBCells6_Therm9_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells6_Therm9_t));

    return 0;
}

uint8_t PCBCells6_Therm9_PCBCells6_Therm9_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells6_Therm9_PCBCells6_Therm9_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells6_Therm9_PCBCells6_Therm9_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells6_Therm8_pack(
    uint8_t *dst_p,
    const struct PCBCells6_Therm8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells6_Therm8_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells6_Therm8_unpack(
    struct PCBCells6_Therm8_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells6_Therm8_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells6_Therm8_init(struct PCBCells6_Therm8_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells6_Therm8_t));

    return 0;
}

uint8_t PCBCells6_Therm8_PCBCells6_Therm8_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells6_Therm8_PCBCells6_Therm8_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells6_Therm8_PCBCells6_Therm8_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells6_Therm7_pack(
    uint8_t *dst_p,
    const struct PCBCells6_Therm7_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells6_Therm7_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells6_Therm7_unpack(
    struct PCBCells6_Therm7_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells6_Therm7_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells6_Therm7_init(struct PCBCells6_Therm7_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells6_Therm7_t));

    return 0;
}

uint8_t PCBCells6_Therm7_PCBCells6_Therm7_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells6_Therm7_PCBCells6_Therm7_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells6_Therm7_PCBCells6_Therm7_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells6_Therm6_pack(
    uint8_t *dst_p,
    const struct PCBCells6_Therm6_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells6_Therm6_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells6_Therm6_unpack(
    struct PCBCells6_Therm6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells6_Therm6_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells6_Therm6_init(struct PCBCells6_Therm6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells6_Therm6_t));

    return 0;
}

uint8_t PCBCells6_Therm6_PCBCells6_Therm6_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells6_Therm6_PCBCells6_Therm6_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells6_Therm6_PCBCells6_Therm6_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells6_Therm5_pack(
    uint8_t *dst_p,
    const struct PCBCells6_Therm5_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells6_Therm5_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells6_Therm5_unpack(
    struct PCBCells6_Therm5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells6_Therm5_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells6_Therm5_init(struct PCBCells6_Therm5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells6_Therm5_t));

    return 0;
}

uint8_t PCBCells6_Therm5_PCBCells6_Therm5_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells6_Therm5_PCBCells6_Therm5_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells6_Therm5_PCBCells6_Therm5_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells6_Therm4_pack(
    uint8_t *dst_p,
    const struct PCBCells6_Therm4_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells6_Therm4_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells6_Therm4_unpack(
    struct PCBCells6_Therm4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells6_Therm4_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells6_Therm4_init(struct PCBCells6_Therm4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells6_Therm4_t));

    return 0;
}

uint8_t PCBCells6_Therm4_PCBCells6_Therm4_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells6_Therm4_PCBCells6_Therm4_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells6_Therm4_PCBCells6_Therm4_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells6_Therm3_pack(
    uint8_t *dst_p,
    const struct PCBCells6_Therm3_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells6_Therm3_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells6_Therm3_unpack(
    struct PCBCells6_Therm3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells6_Therm3_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells6_Therm3_init(struct PCBCells6_Therm3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells6_Therm3_t));

    return 0;
}

uint8_t PCBCells6_Therm3_PCBCells6_Therm3_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells6_Therm3_PCBCells6_Therm3_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells6_Therm3_PCBCells6_Therm3_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells6_Therm2_pack(
    uint8_t *dst_p,
    const struct PCBCells6_Therm2_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells6_Therm2_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells6_Therm2_unpack(
    struct PCBCells6_Therm2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells6_Therm2_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells6_Therm2_init(struct PCBCells6_Therm2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells6_Therm2_t));

    return 0;
}

uint8_t PCBCells6_Therm2_PCBCells6_Therm2_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells6_Therm2_PCBCells6_Therm2_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells6_Therm2_PCBCells6_Therm2_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells6_Therm1_pack(
    uint8_t *dst_p,
    const struct PCBCells6_Therm1_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells6_Therm1_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells6_Therm1_unpack(
    struct PCBCells6_Therm1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells6_Therm1_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells6_Therm1_init(struct PCBCells6_Therm1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells6_Therm1_t));

    return 0;
}

uint8_t PCBCells6_Therm1_PCBCells6_Therm1_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells6_Therm1_PCBCells6_Therm1_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells6_Therm1_PCBCells6_Therm1_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells7_Therm1_pack(
    uint8_t *dst_p,
    const struct PCBCells7_Therm1_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells7_Therm1_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells7_Therm1_unpack(
    struct PCBCells7_Therm1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells7_Therm1_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells7_Therm1_init(struct PCBCells7_Therm1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells7_Therm1_t));

    return 0;
}

uint8_t PCBCells7_Therm1_PCBCells7_Therm1_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells7_Therm1_PCBCells7_Therm1_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells7_Therm1_PCBCells7_Therm1_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells7_Therm2_pack(
    uint8_t *dst_p,
    const struct PCBCells7_Therm2_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells7_Therm2_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells7_Therm2_unpack(
    struct PCBCells7_Therm2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells7_Therm2_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells7_Therm2_init(struct PCBCells7_Therm2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells7_Therm2_t));

    return 0;
}

uint8_t PCBCells7_Therm2_PCBCells7_Therm2_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells7_Therm2_PCBCells7_Therm2_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells7_Therm2_PCBCells7_Therm2_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells7_Therm3_pack(
    uint8_t *dst_p,
    const struct PCBCells7_Therm3_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells7_Therm3_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells7_Therm3_unpack(
    struct PCBCells7_Therm3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells7_Therm3_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells7_Therm3_init(struct PCBCells7_Therm3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells7_Therm3_t));

    return 0;
}

uint8_t PCBCells7_Therm3_PCBCells7_Therm3_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells7_Therm3_PCBCells7_Therm3_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells7_Therm3_PCBCells7_Therm3_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells7_Therm4_pack(
    uint8_t *dst_p,
    const struct PCBCells7_Therm4_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells7_Therm4_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells7_Therm4_unpack(
    struct PCBCells7_Therm4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells7_Therm4_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells7_Therm4_init(struct PCBCells7_Therm4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells7_Therm4_t));

    return 0;
}

uint8_t PCBCells7_Therm4_PCBCells7_Therm4_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells7_Therm4_PCBCells7_Therm4_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells7_Therm4_PCBCells7_Therm4_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells7_Therm5_pack(
    uint8_t *dst_p,
    const struct PCBCells7_Therm5_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells7_Therm5_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells7_Therm5_unpack(
    struct PCBCells7_Therm5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells7_Therm5_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells7_Therm5_init(struct PCBCells7_Therm5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells7_Therm5_t));

    return 0;
}

uint8_t PCBCells7_Therm5_PCBCells7_Therm5_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells7_Therm5_PCBCells7_Therm5_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells7_Therm5_PCBCells7_Therm5_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells7_Therm6_pack(
    uint8_t *dst_p,
    const struct PCBCells7_Therm6_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells7_Therm6_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells7_Therm6_unpack(
    struct PCBCells7_Therm6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells7_Therm6_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells7_Therm6_init(struct PCBCells7_Therm6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells7_Therm6_t));

    return 0;
}

uint8_t PCBCells7_Therm6_PCBCells7_Therm6_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells7_Therm6_PCBCells7_Therm6_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells7_Therm6_PCBCells7_Therm6_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells7_Therm7_pack(
    uint8_t *dst_p,
    const struct PCBCells7_Therm7_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells7_Therm7_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells7_Therm7_unpack(
    struct PCBCells7_Therm7_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells7_Therm7_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells7_Therm7_init(struct PCBCells7_Therm7_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells7_Therm7_t));

    return 0;
}

uint8_t PCBCells7_Therm7_PCBCells7_Therm7_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells7_Therm7_PCBCells7_Therm7_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells7_Therm7_PCBCells7_Therm7_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells7_Therm8_pack(
    uint8_t *dst_p,
    const struct PCBCells7_Therm8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells7_Therm8_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells7_Therm8_unpack(
    struct PCBCells7_Therm8_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells7_Therm8_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells7_Therm8_init(struct PCBCells7_Therm8_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells7_Therm8_t));

    return 0;
}

uint8_t PCBCells7_Therm8_PCBCells7_Therm8_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells7_Therm8_PCBCells7_Therm8_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells7_Therm8_PCBCells7_Therm8_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int PCBCells7_Therm9_pack(
    uint8_t *dst_p,
    const struct PCBCells7_Therm9_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->PCBCells7_Therm9_Temperature, 0u, 0xffu);

    return (1);
}

int PCBCells7_Therm9_unpack(
    struct PCBCells7_Therm9_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->PCBCells7_Therm9_Temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int PCBCells7_Therm9_init(struct PCBCells7_Therm9_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct PCBCells7_Therm9_t));

    return 0;
}

uint8_t PCBCells7_Therm9_PCBCells7_Therm9_Temperature_encode(double value)
{
    return (uint8_t)((value - -49.0) / 0.39216);
}

double PCBCells7_Therm9_PCBCells7_Therm9_Temperature_decode(uint8_t value)
{
    return (((double)value * 0.39216) + -49.0);
}

bool PCBCells7_Therm9_PCBCells7_Therm9_Temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
