/**
 * @file CAN_DB.c
 *
 * @brief This source file was generated by cantools version 0.1.dev1949+g29b75602e.d20260911 Sat Sep 12 14:48:26 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "CAN_DB.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int BMSMaster_NODE_pack(
    uint8_t *dst_p,
    const struct BMSMaster_NODE_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->Error_Code, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->Error_Code, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->Reserved, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->Severity, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u8(src_p->Node_Execution_Halted, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u64(src_p->Error_Specific_Data, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->Error_Specific_Data, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->Error_Specific_Data, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->Error_Specific_Data, 24u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->Error_Specific_Data, 32u, 0xffu);

    return (8);
}

int BMSMaster_NODE_init(struct BMSMaster_NODE_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_NODE_t));

    return 0;
}

uint16_t BMSMaster_NODE_Error_Code_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_NODE_Error_Code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_NODE_Reserved_encode(double value)
{
    return (uint8_t)(value);
}

bool BMSMaster_NODE_Reserved_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t BMSMaster_NODE_Severity_encode(double value)
{
    return (uint8_t)(value);
}

bool BMSMaster_NODE_Severity_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t BMSMaster_NODE_Node_Execution_Halted_encode(double value)
{
    return (uint8_t)(value);
}

bool BMSMaster_NODE_Node_Execution_Halted_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint64_t BMSMaster_NODE_Error_Specific_Data_encode(double value)
{
    return (uint64_t)(value);
}

bool BMSMaster_NODE_Error_Specific_Data_is_in_range(uint64_t value)
{
    return (value <= 1099511627775ull);
}

int BMSMaster_END_pack(
    uint8_t *dst_p,
    const struct BMSMaster_END_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    return (8);
}

int BMSMaster_END_init(struct BMSMaster_END_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_END_t));

    return 0;
}

int BMSMaster_MasterVoltCurrTemp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_MasterVoltCurrTemp_t *src_p,
    size_t size)
{
    uint16_t BMSMaster_MasterBatteryCurrent;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->BMSMaster_MasterBatteryVoltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->BMSMaster_MasterBatteryVoltage, 8u, 0xffu);
    BMSMaster_MasterBatteryCurrent = (uint16_t)src_p->BMSMaster_MasterBatteryCurrent;
    dst_p[2] |= pack_left_shift_u16(BMSMaster_MasterBatteryCurrent, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(BMSMaster_MasterBatteryCurrent, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->BMSMaste_MasterBatteryTemperatur, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->BMSMaste_MasterBatteryTemperatur, 8u, 0xffu);

    return (6);
}

int BMSMaster_MasterVoltCurrTemp_init(struct BMSMaster_MasterVoltCurrTemp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_MasterVoltCurrTemp_t));

    return 0;
}

uint16_t BMSMaster_MasterVoltCurrTemp_BMSMaster_MasterBatteryVoltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

bool BMSMaster_MasterVoltCurrTemp_BMSMaster_MasterBatteryVoltage_is_in_range(uint16_t value)
{
    return ((value >= 630u) && (value <= 870u));
}

int16_t BMSMaster_MasterVoltCurrTemp_BMSMaster_MasterBatteryCurrent_encode(double value)
{
    return (int16_t)(value / 0.1);
}

bool BMSMaster_MasterVoltCurrTemp_BMSMaster_MasterBatteryCurrent_is_in_range(int16_t value)
{
    return ((value >= -3000) && (value <= 3000));
}

uint16_t BMSMaster_MasterVoltCurrTemp_BMSMaste_MasterBatteryTemperatur_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

bool BMSMaster_MasterVoltCurrTemp_BMSMaste_MasterBatteryTemperatur_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

int BMSMaster_PCBsTherm1Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm1Temp_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->BMSMaster_PCB1Therm1Temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->BMSMaster_PCB2Therm1Temp, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->BMSMaster_PCB3Therm1Temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->BMSMaster_PCB4Therm1Temp, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->BMSMaster_PCB5Therm1Temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->BMSMaster_PCB6Therm1Temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->BMSMaster_PCB7Therm1Temp, 0u, 0xffu);

    return (7);
}

int BMSMaster_PCBsTherm1Temp_init(struct BMSMaster_PCBsTherm1Temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_PCBsTherm1Temp_t));

    return 0;
}

uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB1Therm1Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB1Therm1Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB2Therm1Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB2Therm1Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB3Therm1Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB3Therm1Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB4Therm1Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB4Therm1Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB5Therm1Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB5Therm1Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB6Therm1Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB6Therm1Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm1Temp_BMSMaster_PCB7Therm1Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm1Temp_BMSMaster_PCB7Therm1Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int BMSMaster_PCBsTherm2Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm2Temp_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->BMSMaster_PCB1Therm2Temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->BMSMaster_PCB2Therm2Temp, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->BMSMaster_PCB3Therm2Temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->BMSMaster_PCB4Therm2Temp, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->BMSMaster_PCB5Therm2Temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->BMSMaster_PCB6Therm2Temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->BMSMaster_PCB7Therm2Temp, 0u, 0xffu);

    return (7);
}

int BMSMaster_PCBsTherm2Temp_init(struct BMSMaster_PCBsTherm2Temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_PCBsTherm2Temp_t));

    return 0;
}

uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB1Therm2Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB1Therm2Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB2Therm2Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB2Therm2Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB3Therm2Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB3Therm2Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB4Therm2Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB4Therm2Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB5Therm2Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB5Therm2Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB6Therm2Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB6Therm2Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm2Temp_BMSMaster_PCB7Therm2Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm2Temp_BMSMaster_PCB7Therm2Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int BMSMaster_PCBsTherm3Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm3Temp_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->BMSMaster_PCB1Therm3Temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->BMSMaster_PCB2Therm3Temp, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->BMSMaster_PCB3Therm3Temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->BMSMaster_PCB4Therm3Temp, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->BMSMaster_PCB5Therm3Temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->BMSMaster_PCB6Therm3Temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->BMSMaster_PCB7Therm3Temp, 0u, 0xffu);

    return (7);
}

int BMSMaster_PCBsTherm3Temp_init(struct BMSMaster_PCBsTherm3Temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_PCBsTherm3Temp_t));

    return 0;
}

uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB1Therm3Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB1Therm3Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB2Therm3Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB2Therm3Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB3Therm3Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB3Therm3Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB4Therm3Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB4Therm3Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB5Therm3Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB5Therm3Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB6Therm3Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB6Therm3Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm3Temp_BMSMaster_PCB7Therm3Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm3Temp_BMSMaster_PCB7Therm3Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int BMSMaster_PCBsTherm4Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm4Temp_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->BMSMaster_PCB1Therm4Temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->BMSMaster_PCB2Therm4Temp, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->BMSMaster_PCB3Therm4Temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->BMSMaster_PCB4Therm4Temp, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->BMSMaster_PCB5Therm4Temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->BMSMaster_PCB6Therm4Temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->BMSMaster_PCB7Therm4Temp, 0u, 0xffu);

    return (7);
}

int BMSMaster_PCBsTherm4Temp_init(struct BMSMaster_PCBsTherm4Temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_PCBsTherm4Temp_t));

    return 0;
}

uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB1Therm4Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB1Therm4Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB2Therm4Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB2Therm4Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB3Therm4Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB3Therm4Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB4Therm4Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB4Therm4Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB5Therm4Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB5Therm4Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB6Therm4Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB6Therm4Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm4Temp_BMSMaster_PCB7Therm4Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm4Temp_BMSMaster_PCB7Therm4Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int BMSMaster_PCBsTherm5Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm5Temp_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->BMSMaster_PCB1Therm5Temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->BMSMaster_PCB2Therm5Temp, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->BMSMaster_PCB3Therm5Temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->BMSMaster_PCB4Therm5Temp, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->BMSMaster_PCB5Therm5Temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->BMSMaster_PCB6Therm5Temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->BMSMaster_PCB7Therm5Temp, 0u, 0xffu);

    return (7);
}

int BMSMaster_PCBsTherm5Temp_init(struct BMSMaster_PCBsTherm5Temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_PCBsTherm5Temp_t));

    return 0;
}

uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB1Therm5Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB1Therm5Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB2Therm5Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB2Therm5Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB3Therm5Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB3Therm5Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB4Therm5Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB4Therm5Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB5Therm5Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB5Therm5Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB6Therm5Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB6Therm5Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm5Temp_BMSMaster_PCB7Therm5Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm5Temp_BMSMaster_PCB7Therm5Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int BMSMaster_PCBsTherm6Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm6Temp_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->BMSMaster_PCB1Therm6Temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->BMSMaster_PCB2Therm6Temp, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->BMSMaster_PCB3Therm6Temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->BMSMaster_PCB4Therm6Temp, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->BMSMaster_PCB5Therm6Temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->BMSMaster_PCB6Therm6Temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->BMSMaster_PCB7Therm6Temp, 0u, 0xffu);

    return (7);
}

int BMSMaster_PCBsTherm6Temp_init(struct BMSMaster_PCBsTherm6Temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_PCBsTherm6Temp_t));

    return 0;
}

uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB1Therm6Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB1Therm6Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB2Therm6Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB2Therm6Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB3Therm6Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB3Therm6Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB4Therm6Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB4Therm6Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB5Therm6Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB5Therm6Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB6Therm6Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB6Therm6Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm6Temp_BMSMaster_PCB7Therm6Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm6Temp_BMSMaster_PCB7Therm6Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int BMSMaster_PCBsTherm7Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm7Temp_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->BMSMaster_PCB1Therm7Temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->BMSMaster_PCB2Therm7Temp, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->BMSMaster_PCB3Therm7Temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->BMSMaster_PCB4Therm7Temp, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->BMSMaster_PCB5Therm7Temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->BMSMaster_PCB6Therm7Temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->BMSMaster_PCB7Therm7Temp, 0u, 0xffu);

    return (7);
}

int BMSMaster_PCBsTherm7Temp_init(struct BMSMaster_PCBsTherm7Temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_PCBsTherm7Temp_t));

    return 0;
}

uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB1Therm7Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB1Therm7Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB2Therm7Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB2Therm7Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB3Therm7Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB3Therm7Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB4Therm7Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB4Therm7Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB5Therm7Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB5Therm7Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB6Therm7Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB6Therm7Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm7Temp_BMSMaster_PCB7Therm7Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm7Temp_BMSMaster_PCB7Therm7Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int BMSMaster_PCBsTherm8Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm8Temp_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->BMSMaster_PCB1Therm8Temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->BMSMaster_PCB2Therm8Temp, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->BMSMaster_PCB3Therm8Temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->BMSMaster_PCB4Therm8Temp, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->BMSMaster_PCB5Therm8Temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->BMSMaster_PCB6Therm8Temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->BMSMaster_PCB7Therm8Temp, 0u, 0xffu);

    return (7);
}

int BMSMaster_PCBsTherm8Temp_init(struct BMSMaster_PCBsTherm8Temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_PCBsTherm8Temp_t));

    return 0;
}

uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB1Therm8Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB1Therm8Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB2Therm8Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB2Therm8Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB3Therm8Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB3Therm8Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB4Therm8Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB4Therm8Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB5Therm8Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB5Therm8Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB6Therm8Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB6Therm8Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm8Temp_BMSMaster_PCB7Therm8Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm8Temp_BMSMaster_PCB7Therm8Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int BMSMaster_PCBsTherm9Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_PCBsTherm9Temp_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->BMSMaster_PCB1Therm9Temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->BMSMaster_PCB2Therm9Temp, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->BMSMaster_PCB13herm9Temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->BMSMaster_PCB4Therm9Temp, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->BMSMaster_PCB5Therm9Temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->BMSMaster_PCB6Therm9Temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->BMSMaster_PCB7Therm9Temp, 0u, 0xffu);

    return (7);
}

int BMSMaster_PCBsTherm9Temp_init(struct BMSMaster_PCBsTherm9Temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_PCBsTherm9Temp_t));

    return 0;
}

uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB1Therm9Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB1Therm9Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB2Therm9Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB2Therm9Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB13herm9Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB13herm9Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB4Therm9Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB4Therm9Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB5Therm9Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB5Therm9Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB6Therm9Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB6Therm9Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_PCBsTherm9Temp_BMSMaster_PCB7Therm9Temp_encode(double value)
{
    return (uint8_t)(value / 0.39216);
}

bool BMSMaster_PCBsTherm9Temp_BMSMaster_PCB7Therm9Temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int CoolingBack_Fan_unpack(
    struct CoolingBack_Fan_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->SpeedF1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->SpeedF2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int CoolingBack_Fan_init(struct CoolingBack_Fan_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct CoolingBack_Fan_t));

    return 0;
}

double CoolingBack_Fan_SpeedF1_decode(uint8_t value)
{
    return ((double)value);
}

bool CoolingBack_Fan_SpeedF1_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

double CoolingBack_Fan_SpeedF2_decode(uint8_t value)
{
    return ((double)value);
}

bool CoolingBack_Fan_SpeedF2_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

int BMSMaster_JK_Pack_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Pack_t *src_p,
    size_t size)
{
    uint16_t BMSMaster_JK_PackCurrent;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->BMSMaster_JK_PackVoltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->BMSMaster_JK_PackVoltage, 8u, 0xffu);
    BMSMaster_JK_PackCurrent = (uint16_t)src_p->BMSMaster_JK_PackCurrent;
    dst_p[2] |= pack_left_shift_u16(BMSMaster_JK_PackCurrent, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(BMSMaster_JK_PackCurrent, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->BMSMaster_JK_SOC, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->BMSMaster_JK_SOH, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->BMSMaster_JK_StatusFlags, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->BMSMaster_JK_ModeFlags, 0u, 0xffu);

    return (8);
}

int BMSMaster_JK_Pack_init(struct BMSMaster_JK_Pack_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_JK_Pack_t));

    return 0;
}

uint16_t BMSMaster_JK_Pack_BMSMaster_JK_PackVoltage_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

bool BMSMaster_JK_Pack_BMSMaster_JK_PackVoltage_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

int16_t BMSMaster_JK_Pack_BMSMaster_JK_PackCurrent_encode(double value)
{
    return (int16_t)(value / 0.01);
}

bool BMSMaster_JK_Pack_BMSMaster_JK_PackCurrent_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

uint8_t BMSMaster_JK_Pack_BMSMaster_JK_SOC_encode(double value)
{
    return (uint8_t)(value);
}

bool BMSMaster_JK_Pack_BMSMaster_JK_SOC_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t BMSMaster_JK_Pack_BMSMaster_JK_SOH_encode(double value)
{
    return (uint8_t)(value);
}

bool BMSMaster_JK_Pack_BMSMaster_JK_SOH_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t BMSMaster_JK_Pack_BMSMaster_JK_StatusFlags_encode(double value)
{
    return (uint8_t)(value);
}

bool BMSMaster_JK_Pack_BMSMaster_JK_StatusFlags_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_JK_Pack_BMSMaster_JK_ModeFlags_encode(double value)
{
    return (uint8_t)(value);
}

bool BMSMaster_JK_Pack_BMSMaster_JK_ModeFlags_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int BMSMaster_JK_Cells_1_4_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Cells_1_4_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell1_mV, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell1_mV, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell2_mV, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell2_mV, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell3_mV, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell3_mV, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell4_mV, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell4_mV, 8u, 0xffu);

    return (8);
}

int BMSMaster_JK_Cells_1_4_init(struct BMSMaster_JK_Cells_1_4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_JK_Cells_1_4_t));

    return 0;
}

uint16_t BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell1_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell1_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell2_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell2_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell3_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell3_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell4_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_1_4_BMSMaster_JK_Cell4_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

int BMSMaster_JK_Cells_5_8_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Cells_5_8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell5_mV, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell5_mV, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell6_mV, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell6_mV, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell7_mV, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell7_mV, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell8_mV, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell8_mV, 8u, 0xffu);

    return (8);
}

int BMSMaster_JK_Cells_5_8_init(struct BMSMaster_JK_Cells_5_8_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_JK_Cells_5_8_t));

    return 0;
}

uint16_t BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell5_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell5_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell6_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell6_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell7_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell7_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell8_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_5_8_BMSMaster_JK_Cell8_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

int BMSMaster_JK_Cells_9_12_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Cells_9_12_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell9_mV, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell9_mV, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell10_mV, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell10_mV, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell11_mV, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell11_mV, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell12_mV, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell12_mV, 8u, 0xffu);

    return (8);
}

int BMSMaster_JK_Cells_9_12_init(struct BMSMaster_JK_Cells_9_12_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_JK_Cells_9_12_t));

    return 0;
}

uint16_t BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell9_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell9_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell10_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell10_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell11_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell11_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell12_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_9_12_BMSMaster_JK_Cell12_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

int BMSMaster_JK_Cells_13_16_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Cells_13_16_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell13_mV, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell13_mV, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell14_mV, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell14_mV, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell15_mV, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell15_mV, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell16_mV, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell16_mV, 8u, 0xffu);

    return (8);
}

int BMSMaster_JK_Cells_13_16_init(struct BMSMaster_JK_Cells_13_16_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_JK_Cells_13_16_t));

    return 0;
}

uint16_t BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell13_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell13_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell14_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell14_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell15_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell15_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell16_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_13_16_BMSMaster_JK_Cell16_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

int BMSMaster_JK_Cells_17_20_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Cells_17_20_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell17_mV, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell17_mV, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell18_mV, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell18_mV, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell19_mV, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell19_mV, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell20_mV, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell20_mV, 8u, 0xffu);

    return (8);
}

int BMSMaster_JK_Cells_17_20_init(struct BMSMaster_JK_Cells_17_20_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_JK_Cells_17_20_t));

    return 0;
}

uint16_t BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell17_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell17_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell18_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell18_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell19_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell19_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell20_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_17_20_BMSMaster_JK_Cell20_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

int BMSMaster_JK_Cells_21_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Cells_21_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cell21_mV, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cell21_mV, 8u, 0xffu);

    return (2);
}

int BMSMaster_JK_Cells_21_init(struct BMSMaster_JK_Cells_21_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_JK_Cells_21_t));

    return 0;
}

uint16_t BMSMaster_JK_Cells_21_BMSMaster_JK_Cell21_mV_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_Cells_21_BMSMaster_JK_Cell21_mV_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

int BMSMaster_JK_Temp_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_Temp_t *src_p,
    size_t size)
{
    uint8_t BMSMaster_JK_BalTemp;
    uint8_t BMSMaster_JK_MosTemp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    BMSMaster_JK_MosTemp = (uint8_t)src_p->BMSMaster_JK_MosTemp;
    dst_p[0] |= pack_left_shift_u8(BMSMaster_JK_MosTemp, 0u, 0xffu);
    BMSMaster_JK_BalTemp = (uint8_t)src_p->BMSMaster_JK_BalTemp;
    dst_p[1] |= pack_left_shift_u8(BMSMaster_JK_BalTemp, 0u, 0xffu);

    return (8);
}

int BMSMaster_JK_Temp_init(struct BMSMaster_JK_Temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_JK_Temp_t));

    return 0;
}

int8_t BMSMaster_JK_Temp_BMSMaster_JK_MosTemp_encode(double value)
{
    return (int8_t)(value);
}

bool BMSMaster_JK_Temp_BMSMaster_JK_MosTemp_is_in_range(int8_t value)
{
    return ((value >= -40) && (value <= 125));
}

int8_t BMSMaster_JK_Temp_BMSMaster_JK_BalTemp_encode(double value)
{
    return (int8_t)(value);
}

bool BMSMaster_JK_Temp_BMSMaster_JK_BalTemp_is_in_range(int8_t value)
{
    return ((value >= -40) && (value <= 125));
}

int BMSMaster_JK_CycleStats_pack(
    uint8_t *dst_p,
    const struct BMSMaster_JK_CycleStats_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->BMSMaster_JK_Cycles, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->BMSMaster_JK_Cycles, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->BMSMaster_JK_CellCount, 0u, 0xffu);

    return (8);
}

int BMSMaster_JK_CycleStats_init(struct BMSMaster_JK_CycleStats_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct BMSMaster_JK_CycleStats_t));

    return 0;
}

uint16_t BMSMaster_JK_CycleStats_BMSMaster_JK_Cycles_encode(double value)
{
    return (uint16_t)(value);
}

bool BMSMaster_JK_CycleStats_BMSMaster_JK_Cycles_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t BMSMaster_JK_CycleStats_BMSMaster_JK_CellCount_encode(double value)
{
    return (uint8_t)(value);
}

bool BMSMaster_JK_CycleStats_BMSMaster_JK_CellCount_is_in_range(uint8_t value)
{
    return (value <= 32u);
}
